In [85]:
# Enable auto-reloading of modules
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [165]:
from nhl_scraper import scraper
import polars as pl
from tqdm import tqdm

!playwright install

scraper = scraper.Scraper()

In [67]:
data = await scraper.scrape_toi(game_ids=[2024021043, 2024021044],)
data

Scraping NHL TOI Data:   0%|          | 0/2 [00:00<?, ?it/s]

Scraping NHL TOI Data: 100%|██████████| 2/2 [00:02<00:00,  1.21s/it]

{'TOI_combined': shape: (1_604, 14)
 ┌─────────┬──────┬──────────┬───────┬───┬───────────┬─────────────────────┬─────┬────────────┐
 │ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ Duration  ┆ Team                ┆ H/V ┆ gameId     │
 │ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ (Seconds) ┆ ---                 ┆ --- ┆ ---        │
 │ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ ---       ┆ str                 ┆ str ┆ str        │
 │         ┆      ┆          ┆       ┆   ┆ i32       ┆                     ┆     ┆            │
 ╞═════════╪══════╪══════════╪═══════╪═══╪═══════════╪═════════════════════╪═════╪════════════╡
 │ 1       ┆ 1    ┆ 00:47    ┆       ┆ … ┆ 47        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 2       ┆ 1    ┆ 00:32    ┆       ┆ … ┆ 32        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 3       ┆ 1    ┆ 00:56    ┆       ┆ … ┆ 56        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 4       ┆ 1    ┆ 00:40    ┆       ┆ … ┆ 40        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 5       ┆ 1    ┆ 01:21    ┆       ┆ … ┆ 81        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …         ┆ …                   ┆ …   ┆ …          │
 │ 19      ┆ 3    ┆ 00:14    ┆ P     ┆ … ┆ 14        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 20      ┆ 3    ┆ 00:41    ┆       ┆ … ┆ 41        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 21      ┆ 3    ┆ 00:44    ┆       ┆ … ┆ 44        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 22      ┆ 3    ┆ 00:42    ┆       ┆ … ┆ 42        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 23      ┆ null ┆ 01:13    ┆       ┆ … ┆ 73        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 └─────────┴──────┴──────────┴───────┴───┴───────────┴─────────────────────┴─────┴────────────┘,
 'Summary_combined': shape: (251, 17)
 ┌──────┬─────┬───────┬───────┬───┬──────────────────┬─────────────────────┬─────┬────────────┐
 │ Per  ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ SH TOT (Seconds) ┆ Team                ┆ H/V ┆ gameId     │
 │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---                 ┆ --- ┆ ---        │
 │ i32  ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ str                 ┆ str ┆ str        │
 ╞══════╪═════╪═══════╪═══════╪═══╪══════════════════╪═════════════════════╪═════╪════════════╡
 │ 1    ┆ 8   ┆ 00:42 ┆ 05:43 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 2    ┆ 7   ┆ 01:01 ┆ 07:12 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 3    ┆ 7   ┆ 00:51 ┆ 05:58 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 1    ┆ 7   ┆ 01:08 ┆ 08:01 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ 2    ┆ 9   ┆ 00:44 ┆ 06:38 ┆ … ┆ 0                ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
 │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                   ┆ …   ┆ …          │
 │ null ┆ 1   ┆ 00:46 ┆ 00:46 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 1    ┆ 7   ┆ 00:47 ┆ 05:31 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 2    ┆ 7   ┆ 01:00 ┆ 07:01 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ 3    ┆ 8   ┆ 00:44 ┆ 05:53 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 │ null ┆ 1   ┆ 01:13 ┆ 01:13 ┆ … ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
 └──────┴─────┴───────┴───────┴───┴──────────────────┴─────────────────────┴─────┴────────────┘,
 'game_details': {'2024021044': {'GameId': '2024021044',
   'FirstYear': '2024',
   'SecondYear': '2025',
   'ShortId': '021044',
   'season': '2024-2025',
   'Away': 'ST. LOUIS BLUES',
   'Home': 'PITTSBURGH PENGUINS',
   'homeTOI': shape: (384, 13)
   ┌─────────┬─────┬──────────┬───────┬───┬────────────────────────┬───────────┬────────────┬─────┐
   │ Shift # ┆ Per ┆ Duration ┆ Event ┆ … ┆ End Game Time - Legacy ┆ Duration  ┆ Team       ┆ H/V │
   │ ---     ┆ --- ┆ ---      ┆ ---   ┆   ┆ ---                    ┆ (Seconds) ┆ ---        ┆ --- │
   │ i32     ┆ i32 ┆ str      ┆ str   ┆   ┆ str                    ┆ ---       ┆ str        ┆ str │
   │         ┆     ┆          ┆       ┆   ┆                        ┆ i32       ┆            ┆     │
   ╞═════════╪═════╪══════════╪═══════╪═══╪════════════════════════╪═══════════╪════════════╪═════╡
   │ 1       ┆ 1   ┆ 00:46    ┆       ┆ … ┆ 16:57                  ┆ 46        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 2       ┆ 1   ┆ 00:46    ┆       ┆ … ┆ 12:48                  ┆ 46        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 3       ┆ 1   ┆ 00:41    ┆       ┆ … ┆ 5:11                   ┆ 41        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 4       ┆ 1   ┆ 00:17    ┆       ┆ … ┆ 2:24                   ┆ 17        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 5       ┆ 2   ┆ 00:36    ┆       ┆ … ┆ 17:04                  ┆ 36        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ …       ┆ …   ┆ …        ┆ …     ┆ … ┆ …                      ┆ …         ┆ …          ┆ …   │
   │ 19      ┆ 3   ┆ 00:43    ┆       ┆ … ┆ 8:46                   ┆ 43        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 20      ┆ 3   ┆ 00:21    ┆       ┆ … ┆ 7:55                   ┆ 21        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 21      ┆ 3   ┆ 00:56    ┆       ┆ … ┆ 6:13                   ┆ 56        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 22      ┆ 3   ┆ 00:58    ┆       ┆ … ┆ 3:57                   ┆ 58        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   │ 23      ┆ 3   ┆ 00:55    ┆ G     ┆ … ┆ 0:08                   ┆ 55        ┆ PITTSBURGH ┆ H   │
   │         ┆     ┆          ┆       ┆   ┆                        ┆           ┆ PENGUINS   ┆     │
   └─────────┴─────┴──────────┴───────┴───┴────────────────────────┴───────────┴────────────┴─────┘,
   'awayTOI': shape: (396, 13)
   ┌─────────┬─────┬──────────┬───────┬───┬─────────────────┬───────────┬─────────────────┬─────┐
   │ Shift # ┆ Per ┆ Duration ┆ Event ┆ … ┆ End Game Time - ┆ Duration  ┆ Team            ┆ H/V │
   │ ---     ┆ --- ┆ ---      ┆ ---   ┆   ┆ Legacy          ┆ (Seconds) ┆ ---             ┆ --- │
   │ i32     ┆ i32 ┆ str      ┆ str   ┆   ┆ ---             ┆ ---       ┆ str             ┆ str │
   │         ┆     ┆          ┆       ┆   ┆ str             ┆ i32       ┆                 ┆     │
   ╞═════════╪═════╪══════════╪═══════╪═══╪═════════════════╪═══════════╪═════════════════╪═════╡
   │ 1       ┆ 1   ┆ 00:47    ┆       ┆ … ┆ 18:19           ┆ 47        ┆ ST. LOUIS BLUES ┆ V   │
   │ 2       ┆ 1   ┆ 00:32    ┆       ┆ … ┆ 17:11           ┆ 32        ┆ ST. LOUIS BLUES ┆ V   │
   │ 3       ┆ 1   ┆ 00:56    ┆       ┆ … ┆ 13:35           ┆ 56        ┆ ST. LOUIS BLUES ┆ V   │
   │ 4       ┆ 1   ┆ 00:40    ┆       ┆ … ┆ 11:17           ┆ 40        ┆ ST. LOUIS BLUES ┆ V   │
   │ 5       ┆ 1   ┆ 01:21    ┆       ┆ … ┆ 7:06            ┆ 81        ┆ ST. LOUIS BLUES ┆ V   │
   │ …       ┆ …   ┆ …        ┆ …     ┆ … ┆ …               ┆ …         ┆ …               ┆ …   │
   │ 22      ┆ 3   ┆ 00:50    ┆       ┆ … ┆ 9:27            ┆ 50        ┆ ST. LOUIS BLUES ┆ V   │
   │ 23      ┆ 3   ┆ 01:08    ┆       ┆ … ┆ 7:08            ┆ 68        ┆ ST. LOUIS BLUES ┆ V   │
   │ 24      ┆ 3   ┆ 00:39    ┆       ┆ … ┆ 4:51            ┆ 39        ┆ ST. LOUIS BLUES ┆ V   │
   │ 25      ┆ 3   ┆ 02:13    ┆       ┆ … ┆ 0:56            ┆ 133       ┆ ST. LOUIS BLUES ┆ V   │
   │ 26      ┆ 3   ┆ 00:15    ┆ G     ┆ … ┆ 0:08            ┆ 15        ┆ ST. LOUIS BLUES ┆ V   │
   └─────────┴─────┴──────────┴───────┴───┴─────────────────┴───────────┴─────────────────┴─────┘,
   'homeSummary': shape: (57, 16)
   ┌─────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────────┬─────┐
   │ Per ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team                ┆ H/V │
   │ --- ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---                 ┆ --- │
   │ i32 ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ i32              ┆ str                 ┆ str │
   ╞═════╪═════╪═══════╪═══════╪═══╪══════════════════╪══════════════════╪═════════════════════╪═════╡
   │ 1   ┆ 4   ┆ 00:37 ┆ 02:30 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 2   ┆ 5   ┆ 00:39 ┆ 03:17 ┆ … ┆ 0                ┆ 28               ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 3   ┆ 2   ┆ 00:43 ┆ 01:27 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 1   ┆ 4   ┆ 00:44 ┆ 02:58 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 2   ┆ 5   ┆ 00:45 ┆ 03:47 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ …   ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                ┆ …                   ┆ …   │
   │ 2   ┆ 7   ┆ 00:57 ┆ 06:40 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 3   ┆ 6   ┆ 00:48 ┆ 04:51 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 1   ┆ 7   ┆ 00:55 ┆ 06:28 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 2   ┆ 8   ┆ 00:41 ┆ 05:34 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   │ 3   ┆ 8   ┆ 00:47 ┆ 06:23 ┆ … ┆ 0                ┆ 0                ┆ PITTSBURGH PENGUINS ┆ H   │
   └─────┴─────┴───────┴───────┴───┴──────────────────┴──────────────────┴─────────────────────┴─────┘,
   'awaySummary': shape: (58, 16)
   ┌─────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────┬─────┐
   │ Per ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team            ┆ H/V │
   │ --- ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---             ┆ --- │
   │ i32 ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ i32              ┆ str             ┆ str │
   ╞═════╪═════╪═══════╪═══════╪═══╪══════════════════╪══════════════════╪═════════════════╪═════╡
   │ 1   ┆ 8   ┆ 00:42 ┆ 05:43 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 2   ┆ 7   ┆ 01:01 ┆ 07:12 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 3   ┆ 7   ┆ 00:51 ┆ 05:58 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 1   ┆ 7   ┆ 01:08 ┆ 08:01 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 2   ┆ 9   ┆ 00:44 ┆ 06:38 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ …   ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                ┆ …               ┆ …   │
   │ 2   ┆ 8   ┆ 00:44 ┆ 05:56 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 3   ┆ 8   ┆ 00:47 ┆ 06:19 ┆ … ┆ 45               ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 1   ┆ 7   ┆ 00:50 ┆ 05:51 ┆ … ┆ 0                ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 2   ┆ 10  ┆ 00:41 ┆ 06:50 ┆ … ┆ 36               ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   │ 3   ┆ 9   ┆ 00:54 ┆ 08:11 ┆ … ┆ 41               ┆ 0                ┆ ST. LOUIS BLUES ┆ V   │
   └─────┴─────┴───────┴───────┴───┴──────────────────┴──────────────────┴─────────────────┴─────┘},
  '2024021043': {'GameId': '2024021043',
   'FirstYear': '2024',
   'SecondYear': '2025',
   'ShortId': '021043',
   'season': '2024-2025',
   'Away': 'TAMPA BAY LIGHTNING',
   'Home': 'PHILADELPHIA FLYERS',
   'homeTOI': shape: (412, 13)
   ┌─────────┬──────┬──────────┬───────┬───┬─────────────────────────┬───────────┬──────────────┬─────┐
   │ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ End Game Time - Legacy  ┆ Duration  ┆ Team         ┆ H/V │
   │ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ ---                     ┆ (Seconds) ┆ ---          ┆ --- │
   │ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ str                     ┆ ---       ┆ str          ┆ str │
   │         ┆      ┆          ┆       ┆   ┆                         ┆ i32       ┆              ┆     │
   ╞═════════╪══════╪══════════╪═══════╪═══╪═════════════════════════╪═══════════╪══════════════╪═════╡
   │ 1       ┆ 1    ┆ 00:39    ┆       ┆ … ┆ 18:26                   ┆ 39        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 2       ┆ 1    ┆ 01:02    ┆       ┆ … ┆ 15:14                   ┆ 62        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 3       ┆ 1    ┆ 00:36    ┆ P     ┆ … ┆ 13:13                   ┆ 36        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 4       ┆ 1    ┆ 00:42    ┆       ┆ … ┆ 11:48                   ┆ 42        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 5       ┆ 1    ┆ 01:09    ┆       ┆ … ┆ 9:52                    ┆ 69        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …                       ┆ …         ┆ …            ┆ …   │
   │ 19      ┆ 3    ┆ 00:14    ┆ P     ┆ … ┆ 9:06                    ┆ 14        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 20      ┆ 3    ┆ 00:41    ┆       ┆ … ┆ 6:16                    ┆ 41        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 21      ┆ 3    ┆ 00:44    ┆       ┆ … ┆ 3:12                    ┆ 44        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 22      ┆ 3    ┆ 00:42    ┆       ┆ … ┆ 1:04                    ┆ 42        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   │ 23      ┆ null ┆ 01:13    ┆       ┆ … ┆ 0:00                    ┆ 73        ┆ PHILADELPHIA ┆ H   │
   │         ┆      ┆          ┆       ┆   ┆                         ┆           ┆ FLYERS       ┆     │
   └─────────┴──────┴──────────┴───────┴───┴─────────────────────────┴───────────┴──────────────┴─────┘,
   'awayTOI': shape: (412, 13)
   ┌─────────┬──────┬──────────┬───────┬───┬────────────────────────┬───────────┬───────────┬─────┐
   │ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ End Game Time - Legacy ┆ Duration  ┆ Team      ┆ H/V │
   │ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ ---                    ┆ (Seconds) ┆ ---       ┆ --- │
   │ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ str                    ┆ ---       ┆ str       ┆ str │
   │         ┆      ┆          ┆       ┆   ┆                        ┆ i32       ┆           ┆     │
   ╞═════════╪══════╪══════════╪═══════╪═══╪════════════════════════╪═══════════╪═══════════╪═════╡
   │ 1       ┆ 1    ┆ 00:08    ┆       ┆ … ┆ 18:06                  ┆ 8         ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 2       ┆ 1    ┆ 01:05    ┆       ┆ … ┆ 16:13                  ┆ 65        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 3       ┆ 1    ┆ 00:23    ┆ P     ┆ … ┆ 13:13                  ┆ 23        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 4       ┆ 1    ┆ 01:00    ┆       ┆ … ┆ 8:51                   ┆ 60        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 5       ┆ 1    ┆ 00:23    ┆       ┆ … ┆ 8:00                   ┆ 23        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …                      ┆ …         ┆ …         ┆ …   │
   │ 15      ┆ 3    ┆ 01:03    ┆       ┆ … ┆ 13:06                  ┆ 63        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 16      ┆ 3    ┆ 00:11    ┆       ┆ … ┆ 11:11                  ┆ 11        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 17      ┆ 3    ┆ 00:38    ┆       ┆ … ┆ 5:08                   ┆ 38        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 18      ┆ 3    ┆ 00:40    ┆       ┆ … ┆ 2:32                   ┆ 40        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   │ 19      ┆ null ┆ 00:44    ┆       ┆ … ┆ 1:55                   ┆ 44        ┆ TAMPA BAY ┆ V   │
   │         ┆      ┆          ┆       ┆   ┆                        ┆           ┆ LIGHTNING ┆     │
   └─────────┴──────┴──────────┴───────┴───┴────────────────────────┴───────────┴───────────┴─────┘,
   'homeSummary': shape: (68, 16)
   ┌──────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────────┬─────┐
   │ Per  ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team                ┆ H/V │
   │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---                 ┆ --- │
   │ i32  ┆ i32 ┆ str   ┆ str   ┆   ┆ i32              ┆ i32              ┆ str                 ┆ str │
   ╞══════╪═════╪═══════╪═══════╪═══╪══════════════════╪══════════════════╪═════════════════════╪═════╡
   │ 1    ┆ 9   ┆ 00:47 ┆ 07:06 ┆ … ┆ 0                ┆ 42               ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 2    ┆ 6   ┆ 00:53 ┆ 05:21 ┆ … ┆ 0                ┆ 39               ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 3    ┆ 7   ┆ 00:39 ┆ 04:36 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 1    ┆ 10  ┆ 00:49 ┆ 08:15 ┆ … ┆ 0                ┆ 58               ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 2    ┆ 9   ┆ 01:08 ┆ 10:12 ┆ … ┆ 56               ┆ 196              ┆ PHILADELPHIA FLYERS ┆ H   │
   │ …    ┆ …   ┆ …     ┆ …     ┆ … ┆ …                ┆ …                ┆ …                   ┆ …   │
   │ null ┆ 1   ┆ 00:46 ┆ 00:46 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 1    ┆ 7   ┆ 00:47 ┆ 05:31 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 2    ┆ 7   ┆ 01:00 ┆ 07:01 ┆ … ┆ 36               ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ 3    ┆ 8   ┆ 00:44 ┆ 05:53 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   │ null ┆ 1   ┆ 01:13 ┆ 01:13 ┆ … ┆ 0                ┆ 0                ┆ PHILADELPHIA FLYERS ┆ H   │
   └──────┴─────┴───────┴───────┴───┴──────────────────┴──────────────────┴─────────────────────┴─────┘,
   'awaySummary': shape: (68, 16)
   ┌──────┬─────┬───────┬───────┬───┬──────────────────┬──────────────────┬─────────────────────┬─────┐
   │ Per  ┆ SHF ┆ AVG   ┆ TOI   ┆ … ┆ PP TOT (Seconds) ┆ SH TOT (Seconds) ┆ Team                ┆ H/V │
   │ ---  ┆ --- ┆ ---   ┆ ---   ┆   ┆ ---              ┆ ---              ┆ ---                 ┆ --- │

In [68]:
data['TOI_combined']

shape: (1_604, 14)
┌─────────┬──────┬──────────┬───────┬───┬───────────┬─────────────────────┬─────┬────────────┐
│ Shift # ┆ Per  ┆ Duration ┆ Event ┆ … ┆ Duration  ┆ Team                ┆ H/V ┆ gameId     │
│ ---     ┆ ---  ┆ ---      ┆ ---   ┆   ┆ (Seconds) ┆ ---                 ┆ --- ┆ ---        │
│ i32     ┆ i32  ┆ str      ┆ str   ┆   ┆ ---       ┆ str                 ┆ str ┆ str        │
│         ┆      ┆          ┆       ┆   ┆ i32       ┆                     ┆     ┆            │
╞═════════╪══════╪══════════╪═══════╪═══╪═══════════╪═════════════════════╪═════╪════════════╡
│ 1       ┆ 1    ┆ 00:47    ┆       ┆ … ┆ 47        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 2       ┆ 1    ┆ 00:32    ┆       ┆ … ┆ 32        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 3       ┆ 1    ┆ 00:56    ┆       ┆ … ┆ 56        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 4       ┆ 1    ┆ 00:40    ┆       ┆ … ┆ 40        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ 5       ┆ 1    ┆ 01:21    ┆       ┆ … ┆ 81        ┆ ST. LOUIS BLUES     ┆ V   ┆ 2024021044 │
│ …       ┆ …    ┆ …        ┆ …     ┆ … ┆ …         ┆ …                   ┆ …   ┆ …          │
│ 19      ┆ 3    ┆ 00:14    ┆ P     ┆ … ┆ 14        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 20      ┆ 3    ┆ 00:41    ┆       ┆ … ┆ 41        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 21      ┆ 3    ┆ 00:44    ┆       ┆ … ┆ 44        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 22      ┆ 3    ┆ 00:42    ┆       ┆ … ┆ 42        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
│ 23      ┆ null ┆ 01:13    ┆       ┆ … ┆ 73        ┆ PHILADELPHIA FLYERS ┆ H   ┆ 2024021043 │
└─────────┴──────┴──────────┴───────┴───┴───────────┴─────────────────────┴─────┴────────────┘

In [64]:
await scraper.scrape_team_rosters(teams=["MTL", "TOR"], seasons=[20242025], progress=False)

shape: (47, 20)
┌─────────┬─────────────┬───────────┬──────────┬───┬──────────┬────────────┬──────────┬────────────┐
│ id      ┆ headshot    ┆ firstName ┆ lastName ┆ … ┆ season   ┆ fullName   ┆ position ┆ meta_datet │
│ ---     ┆ ---         ┆ ---       ┆ ---      ┆   ┆ ---      ┆ ---        ┆ ---      ┆ ime        │
│ i64     ┆ str         ┆ str       ┆ str      ┆   ┆ i64      ┆ str        ┆ str      ┆ ---        │
│         ┆             ┆           ┆          ┆   ┆          ┆            ┆          ┆ datetime[μ │
│         ┆             ┆           ┆          ┆   ┆          ┆            ┆          ┆ s]         │
╞═════════╪═════════════╪═══════════╪══════════╪═══╪══════════╪════════════╪══════════╪════════════╡
│ 8476981 ┆ https://ass ┆ Josh      ┆ Anderson ┆ … ┆ 20242025 ┆ Josh       ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Anderson   ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8476469 ┆ https://ass ┆ Joel      ┆ Armia    ┆ … ┆ 20242025 ┆ Joel Armia ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆            ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8481540 ┆ https://ass ┆ Cole      ┆ Caufield ┆ … ┆ 20242025 ┆ Cole       ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Caufield   ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8481523 ┆ https://ass ┆ Kirby     ┆ Dach     ┆ … ┆ 20242025 ┆ Kirby Dach ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆            ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8477989 ┆ https://ass ┆ Christian ┆ Dvorak   ┆ … ┆ 20242025 ┆ Christian  ┆ F        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Dvorak     ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ …       ┆ …           ┆ …         ┆ …        ┆ … ┆ …        ┆ …          ┆ …        ┆ …          │
│ 8479026 ┆ https://ass ┆ Philippe  ┆ Myers    ┆ … ┆ 20242025 ┆ Philippe   ┆ D        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Myers      ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8476853 ┆ https://ass ┆ Morgan    ┆ Rielly   ┆ … ┆ 20242025 ┆ Morgan     ┆ D        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Rielly     ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8475690 ┆ https://ass ┆ Chris     ┆ Tanev    ┆ … ┆ 20242025 ┆ Chris      ┆ D        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Tanev      ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8476932 ┆ https://ass ┆ Anthony   ┆ Stolarz  ┆ … ┆ 20242025 ┆ Anthony    ┆ G        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Stolarz    ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
│ 8479361 ┆ https://ass ┆ Joseph    ┆ Woll     ┆ … ┆ 20242025 ┆ Joseph     ┆ G        ┆ 2025-03-20 │
│         ┆ ets.nhle.co ┆           ┆          ┆   ┆          ┆ Woll       ┆          ┆ 06:42:23.1 │
│         ┆ m/mugs/n…   ┆           ┆          ┆   ┆          ┆            ┆          ┆ 40496      │
└─────────┴─────────────┴───────────┴──────────┴───┴──────────┴────────────┴──────────┴────────────┘

In [69]:
await scraper.scrape_team_stats(teams=["MTL", "TOR"], seasons=[20242025], sessions=[2], progress=False)

shape: (55, 26)
┌──────────┬────────────┬───────────┬───────────┬───┬─────────┬────────────┬──────────┬────────────┐
│ playerId ┆ headshot   ┆ firstName ┆ lastName  ┆ … ┆ session ┆ fullName   ┆ position ┆ meta_datet │
│ ---      ┆ ---        ┆ ---       ┆ ---       ┆   ┆ ---     ┆ ---        ┆ ---      ┆ ime        │
│ i64      ┆ str        ┆ str       ┆ str       ┆   ┆ i64     ┆ str        ┆ str      ┆ ---        │
│          ┆            ┆           ┆           ┆   ┆         ┆            ┆          ┆ datetime[μ │
│          ┆            ┆           ┆           ┆   ┆         ┆            ┆          ┆ s]         │
╞══════════╪════════════╪═══════════╪═══════════╪═══╪═════════╪════════════╪══════════╪════════════╡
│ 8475233  ┆ https://as ┆ David     ┆ Savard    ┆ … ┆ 2       ┆ David      ┆ D        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Savard     ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8475848  ┆ https://as ┆ Brendan   ┆ Gallagher ┆ … ┆ 2       ┆ Brendan    ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Gallagher  ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8476469  ┆ https://as ┆ Joel      ┆ Armia     ┆ … ┆ 2       ┆ Joel Armia ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆            ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8476875  ┆ https://as ┆ Mike      ┆ Matheson  ┆ … ┆ 2       ┆ Mike       ┆ D        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Matheson   ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8476981  ┆ https://as ┆ Josh      ┆ Anderson  ┆ … ┆ 2       ┆ Josh       ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Anderson   ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ …        ┆ …          ┆ …         ┆ …         ┆ … ┆ …       ┆ …          ┆ …        ┆ …          │
│ 8481582  ┆ https://as ┆ Nicholas  ┆ Robertson ┆ … ┆ 2       ┆ Nicholas   ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Robertson  ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8482259  ┆ https://as ┆ Bobby     ┆ McMann    ┆ … ┆ 2       ┆ Bobby      ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ McMann     ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8482634  ┆ https://as ┆ Alex      ┆ Steeves   ┆ … ┆ 2       ┆ Alex       ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Steeves    ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8482720  ┆ https://as ┆ Matthew   ┆ Knies     ┆ … ┆ 2       ┆ Matthew    ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Knies      ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
│ 8484901  ┆ https://as ┆ Jacob     ┆ Quillan   ┆ … ┆ 2       ┆ Jacob      ┆ F        ┆ 2025-03-20 │
│          ┆ sets.nhle. ┆           ┆           ┆   ┆         ┆ Quillan    ┆          ┆ 12:10:04.2 │
│          ┆ com/mugs/n ┆           ┆           ┆   ┆         ┆            ┆          ┆ 22546      │
│          ┆ …          ┆           ┆           ┆   ┆         ┆            ┆          ┆            │
└──────────┴────────────┴───────────┴───────────┴───┴─────────┴────────────┴──────────┴────────────┘

In [70]:
await scraper.scrape_standings(date="2025-03-10")

Scraping NHL Standings:   0%|          | 0/1 [00:00<?, ?it/s]

Scraping NHL Standings: 100%|██████████| 1/1 [00:00<00:00,  2.46it/s]

shape: (32, 83)
┌────────────┬────────────┬────────────┬────────────┬───┬──────┬───────────┬───────────┬───────────┐
│ conference ┆ conference ┆ conference ┆ conference ┆ … ┆ wins ┆ abbreviat ┆ division  ┆ conferenc │
│ Abbrev     ┆ HomeSequen ┆ L10Sequenc ┆ Name       ┆   ┆ ---  ┆ ion       ┆ ---       ┆ e         │
│ ---        ┆ ce         ┆ e          ┆ ---        ┆   ┆ i32  ┆ ---       ┆ str       ┆ ---       │
│ str        ┆ ---        ┆ ---        ┆ str        ┆   ┆      ┆ str       ┆           ┆ str       │
│            ┆ i64        ┆ i64        ┆            ┆   ┆      ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪════════════╪═══╪══════╪═══════════╪═══════════╪═══════════╡
│ E          ┆ 3          ┆ 3          ┆ Eastern    ┆ … ┆ 42   ┆ WSH       ┆ Metropoli ┆ Eastern   │
│            ┆            ┆            ┆            ┆   ┆      ┆           ┆ tan       ┆           │
│ W          ┆ 2          ┆ 5          ┆ Western    ┆ … ┆ 44   ┆ WPG       ┆ Central   ┆ Western   │
│ W          ┆ 3          ┆ 2          ┆ Western    ┆ … ┆ 42   ┆ DAL       ┆ Central   ┆ Western   │
│ E          ┆ 4          ┆ 2          ┆ Eastern    ┆ … ┆ 40   ┆ FLA       ┆ Atlantic  ┆ Eastern   │
│ W          ┆ 1          ┆ 4          ┆ Western    ┆ … ┆ 38   ┆ VGK       ┆ Pacific   ┆ Western   │
│ …          ┆ …          ┆ …          ┆ …          ┆ … ┆ …    ┆ …         ┆ …         ┆ …         │
│ W          ┆ 12         ┆ 13         ┆ Western    ┆ … ┆ 27   ┆ SEA       ┆ Pacific   ┆ Western   │
│ E          ┆ 11         ┆ 13         ┆ Eastern    ┆ … ┆ 25   ┆ BUF       ┆ Atlantic  ┆ Eastern   │
│ W          ┆ 8          ┆ 6          ┆ Western    ┆ … ┆ 24   ┆ NSH       ┆ Central   ┆ Western   │
│ W          ┆ 14         ┆ 14         ┆ Western    ┆ … ┆ 20   ┆ CHI       ┆ Central   ┆ Western   │
│ W          ┆ 16         ┆ 15         ┆ Western    ┆ … ┆ 17   ┆ SJS       ┆ Pacific   ┆ Western   │
└────────────┴────────────┴────────────┴────────────┴───┴──────┴───────────┴───────────┴───────────┘

In [71]:
await scraper.scrape_draft(years=[i for i in range(2010, 2025)])

Scraping NHL Draft Data:   0%|          | 0/15 [00:00<?, ?it/s]

Scraping NHL Draft Data: 100%|██████████| 15/15 [00:00<00:00, 48.80it/s]

shape: (3_235, 23)
┌───────┬─────────────┬────────────┬────────┬───┬────────────┬───────────┬────────────┬────────────┐
│ round ┆ pickInRound ┆ overallPic ┆ teamId ┆ … ┆ amateurClu ┆ draftYear ┆ fullName   ┆ meta_datet │
│ ---   ┆ ---         ┆ k          ┆ ---    ┆   ┆ bName      ┆ ---       ┆ ---        ┆ ime        │
│ i64   ┆ i64         ┆ ---        ┆ i64    ┆   ┆ ---        ┆ i64       ┆ str        ┆ ---        │
│       ┆             ┆ i64        ┆        ┆   ┆ str        ┆           ┆            ┆ datetime[μ │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ s]         │
╞═══════╪═════════════╪════════════╪════════╪═══╪════════════╪═══════════╪════════════╪════════════╡
│ 1     ┆ 1           ┆ 1          ┆ 16     ┆ … ┆ Regina     ┆ 2023      ┆ Connor     ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Bedard     ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 2           ┆ 2          ┆ 24     ┆ … ┆ Orebro     ┆ 2023      ┆ Leo        ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Carlsson   ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 3           ┆ 3          ┆ 29     ┆ … ┆ Michigan   ┆ 2023      ┆ Adam       ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Fantilli   ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 4           ┆ 4          ┆ 28     ┆ … ┆ USA U-18   ┆ 2023      ┆ Will Smith ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 1     ┆ 5           ┆ 5          ┆ 8      ┆ … ┆ Kloten     ┆ 2023      ┆ David      ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Reinbacher ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ …     ┆ …           ┆ …          ┆ …      ┆ … ┆ …          ┆ …         ┆ …          ┆ …          │
│ 7     ┆ 27          ┆ 213        ┆ 18     ┆ … ┆ Pardubice  ┆ 2018      ┆ Milan      ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Kloucek    ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 7     ┆ 28          ┆ 214        ┆ 14     ┆ … ┆ Vernon     ┆ 2018      ┆ Ty Taylor  ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 7     ┆ 29          ┆ 215        ┆ 52     ┆ … ┆ Okotoks    ┆ 2018      ┆ Austin     ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Wong       ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
│ 7     ┆ 30          ┆ 216        ┆ 3      ┆ … ┆ St. Sebast ┆ 2018      ┆ Riley      ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆ ian's      ┆           ┆ Hughes     ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆ School     ┆           ┆            ┆ 02382      │
│ 7     ┆ 31          ┆ 217        ┆ 15     ┆ … ┆ Saskatoon  ┆ 2018      ┆ Eric       ┆ 2025-03-20 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆ Florchuk   ┆ 12:11:02.9 │
│       ┆             ┆            ┆        ┆   ┆            ┆           ┆            ┆ 02382      │
└───────┴─────────────┴────────────┴────────┴───┴────────────┴───────────┴────────────┴────────────┘

In [62]:
df = await scraper.scrape_team_schedule(team="MTL", season=20242025)

df

Scraping NHL Team Schedule: 100%|██████████| 1/1 [00:01<00:00,  1.44s/it]

shape: (88, 36)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ season   ┆ gameType ┆ gameDate  ┆ … ┆ winningGo ┆ winningGo ┆ winningGo ┆ meta_date │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ alScorerI ┆ alScorerF ┆ alScorerL ┆ time      │
│ i64        ┆ i64      ┆ i64      ┆ date      ┆   ┆ d         ┆ irstIniti ┆ astName   ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆ ---       ┆ al        ┆ ---       ┆ datetime[ │
│            ┆          ┆          ┆           ┆   ┆ i64       ┆ ---       ┆ str       ┆ μs]       │
│            ┆          ┆          ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024010015 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8482134   ┆ L.        ┆ Tuch      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010022 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8479543   ┆ M.        ┆ Pezzetta  ┆ 2025-03-2 │
│            ┆          ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010038 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8481582   ┆ N.        ┆ Robertson ┆ 2025-03-2 │
│            ┆          ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010055 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ 8481582   ┆ N.        ┆ Robertson ┆ 2025-03-2 │
│            ┆          ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024010073 ┆ 20242025 ┆ 1        ┆ 2024-10-0 ┆ … ┆ 8484759   ┆ C.        ┆ Yakemchuk ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024021236 ┆ 20242025 ┆ 2        ┆ 2025-04-0 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021260 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021269 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 2         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021285 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
│ 2024021301 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ null      ┆ 2025-03-2 │
│            ┆          ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆ 0 06:39:3 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 8.996575  │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [82]:
await scraper.scrape_schedule(teams=["MTL", "TOR"], seasons=[20242025])

Scraping NHL Schedule: 100%|██████████| 2/2 [00:00<00:00,  3.73it/s]

shape: (176, 37)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ season   ┆ gameType ┆ gameDate  ┆ … ┆ winningGo ┆ winningGo ┆ _gameType ┆ meta_date │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ alScorerF ┆ alScorerL ┆ ---       ┆ time      │
│ i64        ┆ i64      ┆ i64      ┆ date      ┆   ┆ irstIniti ┆ astName   ┆ str       ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆ al        ┆ ---       ┆           ┆ datetime[ │
│            ┆          ┆          ┆           ┆   ┆ ---       ┆ str       ┆           ┆ μs]       │
│            ┆          ┆          ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024010015 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ L.        ┆ Tuch      ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010022 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ M.        ┆ Pezzetta  ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 4         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010038 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ N.        ┆ Robertson ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 6         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010055 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ N.        ┆ Robertson ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 8         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024010073 ┆ 20242025 ┆ 1        ┆ 2024-10-0 ┆ … ┆ C.        ┆ Yakemchuk ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ …          ┆ …        ┆ …        ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024021245 ┆ 20242025 ┆ 2        ┆ 2025-04-0 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 9         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021269 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 2         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021279 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021292 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 5         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
│ 2024021308 ┆ 20242025 ┆ 2        ┆ 2025-04-1 ┆ … ┆ null      ┆ null      ┆ regular   ┆ 2025-03-2 │
│            ┆          ┆          ┆ 7         ┆   ┆           ┆           ┆           ┆ 0 12:56:4 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 1.619277  │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [118]:
scraper = scraper.Scraper()
df = await scraper.scrape_teams("active")

df.select(["abbrev"])

Scraping NHL Teams: 100%|██████████| 1/1 [00:00<00:00,  2.76it/s]

shape: (32, 1)
┌────────┐
│ abbrev │
│ ---    │
│ str    │
╞════════╡
│ NJD    │
│ NYI    │
│ NYR    │
│ PHI    │
│ PIT    │
│ …      │
│ MIN    │
│ WPG    │
│ VGK    │
│ SEA    │
│ UTA    │
└────────┘

In [136]:
await scraper.scrape_pbp([2024021043])

Welcome to the NHL Scraper!

My name is Max and I'm the developer of this project and hockey fan. I hope you enjoy using this tool!

This is a work in progress and not all functionalities are available yet.

*** IMPORTANT ***

Make sure to run the following command in the terminal (it might take a while, but it will ensure that the playwright browser is installed):

$ playwright install
or
$ playwright install chromium

***

If you have any questions, please contact me on X: @woumaxx[https://x.com/woumaxx]

Thank you for using the NHL Scraper!

Scraping NHL PBP Data: 100%|██████████| 1/1 [00:01<00:00,  1.93s/it]

shape: (338, 89)
┌─────┬─────┬─────┬───────┬───┬─────────────┬──────────┬────────────┬────────────────────────────┐
│ #   ┆ Per ┆ Str ┆ Event ┆ … ┆ elapsedTime ┆ strength ┆ gameId     ┆ meta_datetime              │
│ --- ┆ --- ┆ --- ┆ ---   ┆   ┆ ---         ┆ ---      ┆ ---        ┆ ---                        │
│ str ┆ str ┆ str ┆ str   ┆   ┆ i64         ┆ str      ┆ str        ┆ datetime[μs]               │
╞═════╪═════╪═════╪═══════╪═══╪═════════════╪══════════╪════════════╪════════════════════════════╡
│ 4   ┆ 1   ┆     ┆ PSTR  ┆ … ┆ 0           ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 5   ┆ 1   ┆ EV  ┆ FAC   ┆ … ┆ 0           ┆ 5v5      ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 6   ┆ 1   ┆ EV  ┆ GIVE  ┆ … ┆ 18          ┆ 5v5      ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 7   ┆ 1   ┆     ┆ STOP  ┆ … ┆ 24          ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 8   ┆ 1   ┆ EV  ┆ FAC   ┆ … ┆ 24          ┆ 5v5      ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ …   ┆ …   ┆ …   ┆ …     ┆ … ┆ …           ┆ …        ┆ …          ┆ …                          │
│ 337 ┆ 5   ┆ EV  ┆ GOAL  ┆ … ┆ 3900        ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 338 ┆ 5   ┆ EV  ┆ SHOT  ┆ … ┆ 3900        ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 339 ┆ 5   ┆     ┆ SOC   ┆ … ┆ null        ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 340 ┆ 5   ┆     ┆ PEND  ┆ … ┆ 3900        ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
│ 341 ┆ 5   ┆     ┆ GEND  ┆ … ┆ 3900        ┆ null     ┆ 2024021043 ┆ 2025-03-21 07:58:24.130341 │
└─────┴─────┴─────┴───────┴───┴─────────────┴──────────┴────────────┴────────────────────────────┘

In [140]:
teams = await scraper.scrape_teams(source="active")

teams

Scraping NHL Teams: 100%|██████████| 1/1 [00:00<00:00,  2.34it/s]

shape: (32, 10)
┌─────┬──────────┬──────────────┬────────┬───┬──────────────┬──────────────┬──────────────┬────────┐
│ id  ┆ seasonId ┆ commonName   ┆ abbrev ┆ … ┆ placeName    ┆ logo         ┆ darkLogo     ┆ french │
│ --- ┆ ---      ┆ ---          ┆ ---    ┆   ┆ ---          ┆ ---          ┆ ---          ┆ ---    │
│ i64 ┆ i64      ┆ str          ┆ str    ┆   ┆ struct[2]    ┆ str          ┆ str          ┆ bool   │
╞═════╪══════════╪══════════════╪════════╪═══╪══════════════╪══════════════╪══════════════╪════════╡
│ 1   ┆ 20242025 ┆ Devils       ┆ NJD    ┆ … ┆ {"New Jersey ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ ",null}      ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 2   ┆ 20242025 ┆ Islanders    ┆ NYI    ┆ … ┆ {"NY Islande ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ rs",null}    ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 3   ┆ 20242025 ┆ Rangers      ┆ NYR    ┆ … ┆ {"NY Rangers ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ ",null}      ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 4   ┆ 20242025 ┆ Flyers       ┆ PHI    ┆ … ┆ {"Philadelph ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ ia","Philade ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆ lphie"…      ┆ logos/…      ┆ logos/…      ┆        │
│ 5   ┆ 20242025 ┆ Penguins     ┆ PIT    ┆ … ┆ {"Pittsburgh ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ ",null}      ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ …   ┆ …        ┆ …            ┆ …      ┆ … ┆ …            ┆ …            ┆ …            ┆ …      │
│ 30  ┆ 20242025 ┆ Wild         ┆ MIN    ┆ … ┆ {"Minnesota" ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ ,null}       ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 52  ┆ 20242025 ┆ Jets         ┆ WPG    ┆ … ┆ {"Winnipeg", ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ null}        ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 54  ┆ 20242025 ┆ Golden       ┆ VGK    ┆ … ┆ {"Vegas",nul ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆ Knights      ┆        ┆   ┆ l}           ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 55  ┆ 20242025 ┆ Kraken       ┆ SEA    ┆ … ┆ {"Seattle",n ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆              ┆        ┆   ┆ ull}         ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
│ 59  ┆ 20242025 ┆ Utah Hockey  ┆ UTA    ┆ … ┆ {"Utah",null ┆ https://asse ┆ https://asse ┆ false  │
│     ┆          ┆ Club         ┆        ┆   ┆ }            ┆ ts.nhle.com/ ┆ ts.nhle.com/ ┆        │
│     ┆          ┆              ┆        ┆   ┆              ┆ logos/…      ┆ logos/…      ┆        │
└─────┴──────────┴──────────────┴────────┴───┴──────────────┴──────────────┴──────────────┴────────┘

In [142]:
schedule = await scraper.scrape_schedule(teams=teams['abbrev'].to_list(), seasons=[20242025])

schedule.head()

Scraping NHL Schedule:   0%|          | 0/32 [00:00<?, ?it/s]

Scraping NHL Schedule: 100%|██████████| 32/32 [00:00<00:00, 50.11it/s]

shape: (5, 38)
┌────────────┬──────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ season   ┆ gameType ┆ gameDate  ┆ … ┆ winningGo ┆ winningGo ┆ _gameType ┆ meta_date │
│ ---        ┆ ---      ┆ ---      ┆ ---       ┆   ┆ alScorerF ┆ alScorerL ┆ ---       ┆ time      │
│ i64        ┆ i64      ┆ i64      ┆ date      ┆   ┆ irstIniti ┆ astName   ┆ str       ┆ ---       │
│            ┆          ┆          ┆           ┆   ┆ al        ┆ ---       ┆           ┆ datetime[ │
│            ┆          ┆          ┆           ┆   ┆ ---       ┆ str       ┆           ┆ μs]       │
│            ┆          ┆          ┆           ┆   ┆ str       ┆           ┆           ┆           │
╞════════════╪══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2024010017 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ L.        ┆ Bichsel   ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 1 08:05:2 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 3.364376  │
│ 2024010046 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ M.        ┆ Duchene   ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 7         ┆   ┆           ┆           ┆           ┆ 1 08:05:2 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 3.364376  │
│ 2024010062 ┆ 20242025 ┆ 1        ┆ 2024-09-2 ┆ … ┆ J.        ┆ Doan      ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 9         ┆   ┆           ┆           ┆           ┆ 1 08:05:2 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 3.364376  │
│ 2024010077 ┆ 20242025 ┆ 1        ┆ 2024-10-0 ┆ … ┆ B.        ┆ Brisson   ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 1         ┆   ┆           ┆           ┆           ┆ 1 08:05:2 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 3.364376  │
│ 2024010089 ┆ 20242025 ┆ 1        ┆ 2024-10-0 ┆ … ┆ S.        ┆ Malinski  ┆ preseason ┆ 2025-03-2 │
│            ┆          ┆          ┆ 3         ┆   ┆           ┆           ┆           ┆ 1 08:05:2 │
│            ┆          ┆          ┆           ┆   ┆           ┆           ┆           ┆ 3.364376  │
└────────────┴──────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [146]:
games = schedule.filter((pl.col("gameType") == 2) & (pl.col("gameState") == "OFF"))["id"].unique().to_list()

df = await scraper.scrape_pbp(game_ids=games[:2])
df.head()

Welcome to the NHL Scraper!

My name is Max and I'm the developer of this project and hockey fan. I hope you enjoy using this tool!

This is a work in progress and not all functionalities are available yet.

*** IMPORTANT ***

Make sure to run the following command in the terminal (it might take a while, but it will ensure that the playwright browser is installed):

$ playwright install
or
$ playwright install chromium

***

If you have any questions, please contact me on X: @woumaxx[https://x.com/woumaxx]

Thank you for using the NHL Scraper!

Scraping NHL PBP Data: 100%|██████████| 2/2 [00:02<00:00,  1.16s/it]

SchemaError: type Int64 is incompatible with expected type Null

In [148]:
games[:2]

[2024020001, 2024020002]

In [166]:
games_list = []
for game in tqdm(games):
    pbps = await scraper.scrape_pbp(game_ids=[game], progress=False)
    games_list.append(pbps)

games_list


df = pl.concat(games_list, how="diagonal", rechunk=True)
df.head()

100%|██████████| 1101/1101 [22:01<00:00,  1.20s/it]

ShapeError: unable to append to a DataFrame of width 94 with a DataFrame of width 90

In [173]:
# Determine data types for each column
column_dtypes = {}
for pbps in games_list:
    for col in pbps.columns:
        if col not in column_dtypes:
            column_dtypes[col] = pbps[col].dtype  # Store the first encountered dtype

# Second pass: normalize by adding missing columns with matching dtypes
all_columns = sorted(all_columns)  # For consistency
games_list_normalized = []
for pbps in games_list:
    missing_cols = [col for col in all_columns if col not in pbps.columns]
    if missing_cols:
        # Add missing columns with nulls and correct dtypes
        new_cols = [
            pl.lit(None).cast(column_dtypes[col]).alias(col)
            for col in missing_cols
        ]
        pbps = pbps.with_columns(new_cols)
    # Reorder columns to match `all_columns`
    pbps = pbps.select(all_columns)
    games_list_normalized.append(pbps)

# Concatenate
df = pl.concat(games_list_normalized, how="diagonal", rechunk=True)
print(df.head())

SchemaError: type String is incompatible with expected type Null

In [169]:
games_list[0].head()

shape: (5, 94)
┌─────┬─────┬─────┬───────┬───┬─────────────┬──────────┬────────────┬────────────────────────────┐
│ #   ┆ Per ┆ Str ┆ Event ┆ … ┆ elapsedTime ┆ strength ┆ gameId     ┆ meta_datetime              │
│ --- ┆ --- ┆ --- ┆ ---   ┆   ┆ ---         ┆ ---      ┆ ---        ┆ ---                        │
│ str ┆ str ┆ str ┆ str   ┆   ┆ i64         ┆ str      ┆ str        ┆ datetime[μs]               │
╞═════╪═════╪═════╪═══════╪═══╪═════════════╪══════════╪════════════╪════════════════════════════╡
│ 4   ┆ 1   ┆     ┆ PSTR  ┆ … ┆ 0           ┆ null     ┆ 2024020001 ┆ 2025-03-21 08:14:08.670442 │
│ 5   ┆ 1   ┆ EV  ┆ FAC   ┆ … ┆ 0           ┆ 5v5      ┆ 2024020001 ┆ 2025-03-21 08:14:08.670442 │
│ 6   ┆ 1   ┆ EV  ┆ HIT   ┆ … ┆ 5           ┆ 5v5      ┆ 2024020001 ┆ 2025-03-21 08:14:08.670442 │
│ 7   ┆ 1   ┆ EV  ┆ SHOT  ┆ … ┆ 8           ┆ 5v5      ┆ 2024020001 ┆ 2025-03-21 08:14:08.670442 │
│ 8   ┆ 1   ┆ EV  ┆ GIVE  ┆ … ┆ 19          ┆ 5v5      ┆ 2024020001 ┆ 2025-03-21 08:14:08.670442 │
└─────┴─────┴─────┴───────┴───┴─────────────┴──────────┴────────────┴────────────────────────────┘

In [174]:
import polars as pl
from tqdm import tqdm

# Assuming games_list is already populated from your earlier code
# games_list = [...]  # Your scraped DataFrames are here

# Step 1: Identify all unique columns across all DataFrames
all_columns = set()
for pbps in games_list:
    all_columns.update(pbps.columns)
all_columns = sorted(all_columns)  # For consistent ordering

# Step 2: Determine data types for each column
column_dtypes = {}
for pbps in games_list:
    for col in pbps.columns:
        if col not in column_dtypes:
            column_dtypes[col] = pbps[col].dtype  # Take the first encountered dtype

# Step 3: Normalize each DataFrame by adding missing columns with correct dtypes
games_list_normalized = []
for pbps in tqdm(games_list, desc="Normalizing DataFrames"):
    missing_cols = [col for col in all_columns if col not in pbps.columns]
    if missing_cols:
        # Add missing columns with nulls, matching the dtype
        new_cols = [
            pl.lit(None, dtype=column_dtypes[col]).alias(col)
            for col in missing_cols
        ]
        pbps = pbps.with_columns(new_cols)
    # Reorder columns to match all_columns
    pbps = pbps.select(all_columns)
    games_list_normalized.append(pbps)

# Step 4: Concatenate with a fallback to relaxed mode if needed
try:
    df = pl.concat(games_list_normalized, how="diagonal", rechunk=True)
    print("Concatenation successful with strict diagonal!")
except pl.exceptions.SchemaError as e:
    print(f"Strict diagonal failed: {e}. Trying relaxed diagonal...")
    df = pl.concat(games_list_normalized, how="diagonal_relaxed", rechunk=True)
    print("Concatenation successful with relaxed diagonal!")

# Check the result
print(df.head())

Normalizing DataFrames: 100%|██████████| 1101/1101 [00:00<00:00, 1652.62it/s]

Strict diagonal failed: type String is incompatible with expected type Null. Trying relaxed diagonal...
Concatenation successful with relaxed diagonal!
shape: (5, 139)
┌─────┬─────────────────────────────────┬───────┬─────┬───┬────────┬──────┬────────┬──────────┐
│ #   ┆ Description                     ┆ Event ┆ Per ┆ … ┆ xCoord ┆ y    ┆ yCoord ┆ zoneCode │
│ --- ┆ ---                             ┆ ---   ┆ --- ┆   ┆ ---    ┆ ---  ┆ ---    ┆ ---      │
│ str ┆ str                             ┆ str   ┆ str ┆   ┆ f64    ┆ f64  ┆ f64    ┆ str      │
╞═════╪═════════════════════════════════╪═══════╪═════╪═══╪════════╪══════╪════════╪══════════╡
│ 4   ┆ Period Start- Local time: 7:14… ┆ PSTR  ┆ 1   ┆ … ┆ null   ┆ null ┆ null   ┆ null     │
│ 5   ┆ NJD won Neu. Zone - NJD #13 HI… ┆ FAC   ┆ 1   ┆ … ┆ 0.0    ┆ -0.0 ┆ 0.0    ┆ N        │
│ 6   ┆ BUF #29 MALENSTYN HIT NJD #90 … ┆ HIT   ┆ 1   ┆ … ┆ 69.0   ┆ 40.0 ┆ -40.0  ┆ N        │
│ 7   ┆ NJD ONGOAL - #17 NEMEC, Wrist … ┆ SHOT  ┆ 1   ┆ … ┆ 57.0   ┆ 40.0 ┆ -40.0  ┆ O        │
│ 8   ┆ NJD GIVEAWAY - #25 MARKSTROM, … ┆ GIVE  ┆ 1   ┆ … ┆ -73.0  ┆ -9.0 ┆ 9.0    ┆ D        │
└─────┴─────────────────────────────────┴───────┴─────┴───┴────────┴──────┴────────┴──────────┘

In [180]:
# Filter out null columns
# Identify columns where all values are null
null_columns = [col for col in df.columns if df[col].is_null().all()]

# Drop those columns
df = df.drop(null_columns)

df.head()

shape: (5, 119)
┌─────┬─────────────────────────────────┬───────┬─────┬───┬────────┬──────┬────────┬──────────┐
│ #   ┆ Description                     ┆ Event ┆ Per ┆ … ┆ xCoord ┆ y    ┆ yCoord ┆ zoneCode │
│ --- ┆ ---                             ┆ ---   ┆ --- ┆   ┆ ---    ┆ ---  ┆ ---    ┆ ---      │
│ str ┆ str                             ┆ str   ┆ str ┆   ┆ f64    ┆ f64  ┆ f64    ┆ str      │
╞═════╪═════════════════════════════════╪═══════╪═════╪═══╪════════╪══════╪════════╪══════════╡
│ 4   ┆ Period Start- Local time: 7:14… ┆ PSTR  ┆ 1   ┆ … ┆ null   ┆ null ┆ null   ┆ null     │
│ 5   ┆ NJD won Neu. Zone - NJD #13 HI… ┆ FAC   ┆ 1   ┆ … ┆ 0.0    ┆ -0.0 ┆ 0.0    ┆ N        │
│ 6   ┆ BUF #29 MALENSTYN HIT NJD #90 … ┆ HIT   ┆ 1   ┆ … ┆ 69.0   ┆ 40.0 ┆ -40.0  ┆ N        │
│ 7   ┆ NJD ONGOAL - #17 NEMEC, Wrist … ┆ SHOT  ┆ 1   ┆ … ┆ 57.0   ┆ 40.0 ┆ -40.0  ┆ O        │
│ 8   ┆ NJD GIVEAWAY - #25 MARKSTROM, … ┆ GIVE  ┆ 1   ┆ … ┆ -73.0  ┆ -9.0 ┆ 9.0    ┆ D        │
└─────┴─────────────────────────────────┴───────┴─────┴───┴────────┴──────┴────────┴──────────┘

In [198]:
df.filter((pl.col("Event") == "GOAL") 
          & (pl.col("periodNumber") < 5)
        #   & (pl.col("Str") == "PP")
          & (pl.col("playerName_1") == "Patrik Laine")
          )["Str"].value_counts()

shape: (2, 2)
┌─────┬───────┐
│ Str ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ PP  ┆ 11    │
│ EV  ┆ 3     │
└─────┴───────┘

In [196]:
import os

# Create data directory if it doesn't exist
data_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath("pbp.parquet"))), "data")
os.makedirs(data_dir, exist_ok=True)

# Save the parquet file to the data directory
df.write_parquet(os.path.join(data_dir, "pbp.parquet"))

print(f"Parquet file saved to {data_dir}")

Parquet file saved to /Users/max/Documents/nhl_scraper/data

In [197]:
df = pl.read_parquet(os.path.join(data_dir, "pbp.parquet"))
df.head()

shape: (5, 119)
┌─────┬─────────────────────────────────┬───────┬─────┬───┬────────┬──────┬────────┬──────────┐
│ #   ┆ Description                     ┆ Event ┆ Per ┆ … ┆ xCoord ┆ y    ┆ yCoord ┆ zoneCode │
│ --- ┆ ---                             ┆ ---   ┆ --- ┆   ┆ ---    ┆ ---  ┆ ---    ┆ ---      │
│ str ┆ str                             ┆ str   ┆ str ┆   ┆ f64    ┆ f64  ┆ f64    ┆ str      │
╞═════╪═════════════════════════════════╪═══════╪═════╪═══╪════════╪══════╪════════╪══════════╡
│ 4   ┆ Period Start- Local time: 7:14… ┆ PSTR  ┆ 1   ┆ … ┆ null   ┆ null ┆ null   ┆ null     │
│ 5   ┆ NJD won Neu. Zone - NJD #13 HI… ┆ FAC   ┆ 1   ┆ … ┆ 0.0    ┆ -0.0 ┆ 0.0    ┆ N        │
│ 6   ┆ BUF #29 MALENSTYN HIT NJD #90 … ┆ HIT   ┆ 1   ┆ … ┆ 69.0   ┆ 40.0 ┆ -40.0  ┆ N        │
│ 7   ┆ NJD ONGOAL - #17 NEMEC, Wrist … ┆ SHOT  ┆ 1   ┆ … ┆ 57.0   ┆ 40.0 ┆ -40.0  ┆ O        │
│ 8   ┆ NJD GIVEAWAY - #25 MARKSTROM, … ┆ GIVE  ┆ 1   ┆ … ┆ -73.0  ┆ -9.0 ┆ 9.0    ┆ D        │
└─────┴─────────────────────────────────┴───────┴─────┴───┴────────┴──────┴────────┴──────────┘

In [200]:
df.filter((pl.col("Event") == "GOAL") 
          & (pl.col("periodNumber") < 5)
          & ((pl.col("playerName_2") == "Lane Hutson") | (pl.col("playerName_3") == "Lane Hutson"))
          )["Str"].value_counts()

shape: (2, 2)
┌─────┬───────┐
│ Str ┆ count │
│ --- ┆ ---   │
│ str ┆ u32   │
╞═════╪═══════╡
│ EV  ┆ 18    │
│ PP  ┆ 17    │
└─────┴───────┘