In [1]:
# Enable auto-reloading of modules
%load_ext autoreload
%autoreload 2

In [2]:
# Import required packages
import pandas as pd
# from nhl_scraper.scraper.draft import scrapeDraft, scrapeRankings, scrapeDraftLegacy
# from nhl_scraper.scraper.game import scrapeGamePlayByPlay, scrapeGameRosters, scrapeGameShifts, scrapeGameShiftsLegacy, scrapeGameComplete, scrape_html_events
# from nhl_scraper.scraper.player import scrapePlayerProfile, scrapePlayerStats, scrapePlayerGameLog
# from nhl_scraper.scraper.teams import *
# from nhl_scraper.scraper.tools import *
# from nhl_scraper.scraper.nhledge.skater.overview import *
# from nhl_scraper.scraper.nhledge.skater.speed import *
import polars as pl
import nhl_scraper.scraper.scrape.scrape as scrape
from ftfy import fix_text
from datetime import datetime
from typing import Union
import requests
import warnings

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)
pd.set_option('display.encoding', 'utf-8')

pl.Config(tbl_cols=-1)

In [47]:
scrape.scrapeGamePlays(2024020170)

shape: (355, 47)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ eve ┆ tim ┆ tim ┆ sit ┆ hom ┆ typ ┆ typ ┆ sor ┆ per ┆ per ┆ per ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ ppt ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ det ┆ gam ┆ ela ┆ met ┆ met │
│ ntI ┆ eIn ┆ eRe ┆ uat ┆ eTe ┆ eCo ┆ eDe ┆ tOr ┆ iod ┆ iod ┆ iod ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ Rep ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ ail ┆ eId ┆ pse ┆ a_d ┆ a_s │
│ d   ┆ Per ┆ mai ┆ ion ┆ amD ┆ de  ┆ scK ┆ der ┆ Des ┆ Des ┆ Des ┆ s.e ┆ s.l ┆ s.w ┆ s.x ┆ s.y ┆ s.z ┆ s.h ┆ s.h ┆ s.p ┆ s.r ┆ s.s ┆ s.s ┆ s.g ┆ s.b ┆ s.a ┆ s.h ┆ lay ┆ s.s ┆ s.s ┆ s.a ┆ s.a ┆ s.a ┆ s.h ┆ s.h ┆ s.h ┆ s.d ┆ s.s ┆ s.t ┆ s.d ┆ s.d ┆ s.c ┆ s.d ┆ --- ┆ dSe ┆ ate ┆ our │
│ --- ┆ iod ┆ nin ┆ Cod ┆ efe ┆ --- ┆ ey  ┆ --- ┆ cri ┆ cri ┆ cri ┆ ven ┆ osi ┆ inn ┆ Coo ┆ Coo ┆ one ┆ itt ┆ itt ┆ lay ┆ eas ┆ hot ┆ hoo ┆ oal ┆ loc ┆ way ┆ ome ┆ Url ┆ cor ┆ cor ┆ ssi ┆ ssi ┆ way ┆ ome ┆ igh ┆ igh ┆ isc ┆ eco ┆ ype ┆ esc ┆ ura ┆ omm ┆ raw ┆ i32 ┆ con ┆ tim ┆ ce  │
│ i64 ┆ --- ┆ g   ┆ e   ┆ ndi ┆ i64 ┆ --- ┆ i64 ┆ pto ┆ pto ┆ pto ┆ tOw ┆ ngP ┆ ing ┆ rd  ┆ rd  ┆ Cod ┆ ing ┆ eeP ┆ erI ┆ on  ┆ Typ ┆ tin ┆ ieI ┆ kin ┆ SOG ┆ SOG ┆ --- ┆ ing ┆ ing ┆ st1 ┆ st1 ┆ Sco ┆ Sco ┆ lig ┆ lig ┆ ret ┆ nda ┆ Cod ┆ Key ┆ tio ┆ itt ┆ nBy ┆     ┆ ds  ┆ e   ┆ --- │
│     ┆ str ┆ --- ┆ --- ┆ ngS ┆     ┆ str ┆     ┆ r.n ┆ r.p ┆ r.m ┆ ner ┆ lay ┆ Pla ┆ --- ┆ --- ┆ e   ┆ Pla ┆ lay ┆ d   ┆ --- ┆ e   ┆ gPl ┆ nNe ┆ gPl ┆ --- ┆ --- ┆ str ┆ Pla ┆ Pla ┆ Pla ┆ Pla ┆ re  ┆ re  ┆ htC ┆ htC ┆ eCl ┆ ryR ┆ e   ┆ --- ┆ n   ┆ edB ┆ Pla ┆     ┆ --- ┆ --- ┆ str │
│     ┆     ┆ str ┆ str ┆ ide ┆     ┆     ┆     ┆ umb ┆ eri ┆ axR ┆ Tea ┆ erI ┆ yer ┆ i64 ┆ i64 ┆ --- ┆ yer ┆ erI ┆ --- ┆ str ┆ --- ┆ aye ┆ tId ┆ aye ┆ i64 ┆ i64 ┆     ┆ yer ┆ yer ┆ yer ┆ yer ┆ --- ┆ --- ┆ lip ┆ lip ┆ ip  ┆ eas ┆ --- ┆ str ┆ --- ┆ yPl ┆ yer ┆     ┆ i64 ┆ dat ┆     │
│     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆ er  ┆ odT ┆ egu ┆ mId ┆ d   ┆ Id  ┆     ┆     ┆ str ┆ Id  ┆ d   ┆ i64 ┆     ┆ str ┆ rId ┆ --- ┆ rId ┆     ┆     ┆     ┆ Id  ┆ Tot ┆ Id  ┆ Tot ┆ i64 ┆ i64 ┆ Sha ┆ --- ┆ --- ┆ on  ┆ str ┆     ┆ i64 ┆ aye ┆ Id  ┆     ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ ype ┆ lat ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆ --- ┆ i64 ┆ --- ┆     ┆     ┆     ┆ --- ┆ al  ┆ --- ┆ al  ┆     ┆     ┆ rin ┆ i64 ┆ i64 ┆ --- ┆     ┆     ┆     ┆ rId ┆ --- ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ --- ┆ ion ┆ i64 ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆     ┆     ┆     ┆ i64 ┆ --- ┆ i64 ┆ --- ┆     ┆     ┆ gUr ┆     ┆     ┆ str ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆ μs] ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ i64 ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 52  ┆ 00: ┆ 20: ┆ 155 ┆ rig ┆ 520 ┆ per ┆ 8   ┆ 1   ┆ REG ┆ 3   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ 0   ┆ 202 ┆ NHL │
│     ┆ 00  ┆ 00  ┆ 1   ┆ ht  ┆     ┆ iod ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 402 ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆ -st ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ art ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 737 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 640 ┆     │
│ 51  ┆ 00: ┆ 20: ┆ 155 ┆ rig ┆ 502 ┆ fac ┆ 11  ┆ 1   ┆ REG ┆ 3   ┆ 3   ┆ 848 ┆ 847 ┆ 0   ┆ 0   ┆ N   ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ 0   ┆ 202 ┆ NHL │
│     ┆ 00  ┆ 00  ┆ 1   ┆ ht  ┆     ┆ eof ┆     ┆     ┆     ┆     ┆     ┆ 211 ┆ 645 ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 402 ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆ f   ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 737 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 640 ┆     │
│ 119 ┆ 00: ┆ 19: ┆ 155 ┆ rig ┆ 503 ┆ hit ┆ 12  ┆ 1   ┆ REG ┆ 3   ┆ 3   ┆ nul ┆ nul ┆ -96 ┆ 17  ┆ N   ┆ 847 ┆ 847 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ 8   ┆ 202 ┆ NHL │
│     ┆ 08  ┆ 52  ┆ 1   ┆ ht  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆     ┆ 645 ┆ 532 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 402 ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 737 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 640 ┆     │
│ 130 ┆ 00: ┆ 19: ┆ 155 ┆ rig ┆ 504 ┆ giv ┆ 22  ┆ 1   ┆ REG ┆ 3   ┆ 9   ┆ nul ┆ nul ┆ 0   ┆ -33 ┆ N   ┆ nul ┆ nul ┆ 848 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ 46  ┆ 202 ┆ NHL │
│     ┆ 46  ┆ 14  ┆ 1   ┆ ht  ┆     ┆ eaw ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆     ┆ l   ┆ l   ┆ 020 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 402 ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆ ay  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 737 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 640 ┆     │
│ 134 ┆ 01: ┆ 18: ┆ 155 ┆ rig ┆ 504 ┆ giv ┆ 24  ┆ 1   ┆ REG ┆ 3   ┆ 9   ┆ nul ┆ nul ┆ -87 ┆ -8  ┆ D   ┆ nul ┆ nul ┆ 848 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ 65  ┆ 202 ┆ NHL │
│     ┆ 05  ┆ 55  ┆ 1   ┆ ht  ┆     ┆ eaw ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆     ┆ l   ┆ l   ┆ 210 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 402 ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆ ay  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 737 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 640 ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 113 ┆ 19: ┆ 00: ┆ 065 ┆ rig ┆ 507 ┆ mis ┆ 886 ┆ 3   ┆ REG ┆ 3   ┆ 9   ┆ nul ┆ nul ┆ 79  ┆ 2   ┆ O   ┆ nul ┆ nul ┆ nul ┆ wid ┆ wri ┆ 848 ┆ 847 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 202 ┆ 358 ┆ 202 ┆ NHL │
│ 4   ┆ 46  ┆ 14  ┆ 1   ┆ ht  ┆     ┆ sed ┆     ┆     ┆     ┆     ┆     ┆ l   ┆ l   ┆     ┆     ┆     ┆ l   ┆ l   ┆ l   ┆ e-l ┆ st  ┆ 080 ┆ 804 ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ 402 ┆ 6   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆ -sh ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eft ┆     ┆ 1   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 017 ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ ot  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 47: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 01. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 737 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 640 ┆     │

In [34]:
scrape.scrapeGameRosters(2024020170)

shape: (40, 21)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ tea ┆ pla ┆ swe ┆ pos ┆ hea ┆ fir ┆ las ┆ las ┆ las ┆ las ┆ fir ┆ fir ┆ las ┆ las ┆ las ┆ pla ┆ tea ┆ is_ ┆ gam ┆ met ┆ met │
│ mId ┆ yer ┆ ate ┆ iti ┆ dsh ┆ stN ┆ tNa ┆ tNa ┆ tNa ┆ tNa ┆ stN ┆ stN ┆ tNa ┆ tNa ┆ tNa ┆ yer ┆ mAb ┆ hom ┆ eId ┆ a_d ┆ a_s │
│ --- ┆ Id  ┆ rNu ┆ onC ┆ ot  ┆ ame ┆ me. ┆ me. ┆ me. ┆ me. ┆ ame ┆ ame ┆ me. ┆ me. ┆ me. ┆ Nam ┆ bre ┆ e   ┆ --- ┆ ate ┆ our │
│ i64 ┆ --- ┆ mbe ┆ ode ┆ --- ┆ .de ┆ def ┆ cs  ┆ fi  ┆ sk  ┆ .cs ┆ .sk ┆ de  ┆ es  ┆ sv  ┆ e   ┆ v   ┆ --- ┆ i32 ┆ tim ┆ ce  │
│     ┆ i64 ┆ r   ┆ --- ┆ str ┆ fau ┆ aul ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ i8  ┆     ┆ e   ┆ --- │
│     ┆     ┆ --- ┆ str ┆     ┆ lt  ┆ t   ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆     ┆     ┆ --- ┆ str │
│     ┆     ┆ i64 ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     │
│     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 3   ┆ 847 ┆ 32  ┆ G   ┆ htt ┆ Jon ┆ Qui ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Jon ┆ NYR ┆ 1   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 173 ┆     ┆     ┆ ps: ┆ ath ┆ ck  ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ath ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 4   ┆     ┆     ┆ //a ┆ an  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Qui ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ck  ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ 847 ┆ 28  ┆ R   ┆ htt ┆ Cla ┆ Gir ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Cla ┆ OTT ┆ 0   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 351 ┆     ┆     ┆ ps: ┆ ude ┆ oux ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ude ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 2   ┆     ┆     ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gir ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oux ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ 847 ┆ 23  ┆ D   ┆ htt ┆ Tra ┆ Ham ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Tra ┆ OTT ┆ 0   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 461 ┆     ┆     ┆ ps: ┆ vis ┆ oni ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ vis ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 2   ┆     ┆     ┆ //a ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ham ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ oni ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ 847 ┆ 20  ┆ L   ┆ htt ┆ Chr ┆ Kre ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Chr ┆ NYR ┆ 1   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 518 ┆     ┆     ┆ ps: ┆ is  ┆ ide ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ is  ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 4   ┆     ┆     ┆ //a ┆     ┆ r   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Kre ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ide ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ r   ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ 847 ┆ 91  ┆ R   ┆ htt ┆ Rei ┆ Smi ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Rei ┆ NYR ┆ 1   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 519 ┆     ┆     ┆ ps: ┆ lly ┆ th  ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ lly ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 1   ┆     ┆     ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Smi ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ th  ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 3   ┆ 848 ┆ 13  ┆ L   ┆ htt ┆ Ale ┆ Laf ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Ale ┆ NYR ┆ 1   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 210 ┆     ┆     ┆ ps: ┆ xis ┆ ren ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ xis ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 9   ┆     ┆     ┆ //a ┆     ┆ ièr ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Laf ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ren ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ièr ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ 848 ┆ 18  ┆ C   ┆ htt ┆ Tim ┆ Stü ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Tim ┆ OTT ┆ 0   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 211 ┆     ┆     ┆ ps: ┆     ┆ tzl ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ Stü ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 6   ┆     ┆     ┆ //a ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tzl ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ 848 ┆ 50  ┆ L   ┆ htt ┆ Wil ┆ Cuy ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Wil ┆ NYR ┆ 1   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 215 ┆     ┆     ┆ ps: ┆ l   ┆ lle ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 7   ┆     ┆     ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Cuy ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lle ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 9   ┆ 848 ┆ 38  ┆ C   ┆ htt ┆ Zac ┆ Ost ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Zac ┆ OTT ┆ 0   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 285 ┆     ┆     ┆ ps: ┆ k   ┆ apc ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ k   ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 9   ┆     ┆     ┆ //a ┆     ┆ huk ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Ost ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ apc ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ huk ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 3   ┆ 848 ┆ 90  ┆ D   ┆ htt ┆ Vic ┆ Man ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Vic ┆ NYR ┆ 1   ┆ 202 ┆ 202 ┆ NHL │
│     ┆ 376 ┆     ┆     ┆ ps: ┆ tor ┆ cin ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ tor ┆     ┆     ┆ 402 ┆ 5-0 ┆ API │
│     ┆ 8   ┆     ┆     ┆ //a ┆     ┆ i   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Man ┆     ┆     ┆ 017 ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cin ┆     ┆     ┆ 0   ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 42. ┆     │
│     ┆     ┆     ┆     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 466 ┆     │
│     ┆     ┆     ┆     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 354 ┆     │
│     ┆     ┆     ┆     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [27]:
scrape.scrapeTeamProspects("MTL")

shape: (33, 27)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pla ┆ hea ┆ swe ┆ pos ┆ sho ┆ hei ┆ wei ┆ hei ┆ wei ┆ bir ┆ bir ┆ fir ┆ las ┆ bir ┆ bir ┆ bir ┆ bir ┆ bir ┆ bir ┆ bir ┆ bir ┆ bir ┆ bir ┆ ful ┆ tea ┆ met ┆ met │
│ yer ┆ dsh ┆ ate ┆ iti ┆ ots ┆ ght ┆ ght ┆ ght ┆ ght ┆ thD ┆ thC ┆ stN ┆ tNa ┆ thC ┆ thS ┆ thC ┆ thC ┆ thC ┆ thC ┆ thS ┆ thS ┆ thS ┆ thC ┆ lNa ┆ m   ┆ a_d ┆ a_s │
│ Id  ┆ ot  ┆ rNu ┆ onC ┆ Cat ┆ InI ┆ InP ┆ InC ┆ InK ┆ ate ┆ oun ┆ ame ┆ me. ┆ ity ┆ tat ┆ ity ┆ ity ┆ ity ┆ ity ┆ tat ┆ tat ┆ tat ┆ ity ┆ me  ┆ --- ┆ ate ┆ our │
│ --- ┆ --- ┆ mbe ┆ ode ┆ che ┆ nch ┆ oun ┆ ent ┆ ilo ┆ --- ┆ try ┆ .de ┆ def ┆ .de ┆ ePr ┆ .cs ┆ .fi ┆ .fr ┆ .sk ┆ ePr ┆ ePr ┆ ePr ┆ .sv ┆ --- ┆ str ┆ tim ┆ ce  │
│ i64 ┆ str ┆ r   ┆ --- ┆ s   ┆ es  ┆ ds  ┆ ime ┆ gra ┆ dat ┆ --- ┆ fau ┆ aul ┆ fau ┆ ovi ┆ --- ┆ --- ┆ --- ┆ --- ┆ ovi ┆ ovi ┆ ovi ┆ --- ┆ str ┆     ┆ e   ┆ --- │
│     ┆     ┆ --- ┆ str ┆ --- ┆ --- ┆ --- ┆ ter ┆ ms  ┆ e   ┆ str ┆ lt  ┆ t   ┆ lt  ┆ nce ┆ str ┆ str ┆ str ┆ str ┆ nce ┆ nce ┆ nce ┆ str ┆     ┆     ┆ --- ┆ str │
│     ┆     ┆ i64 ┆     ┆ str ┆ i64 ┆ i64 ┆ s   ┆ --- ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ .de ┆     ┆     ┆     ┆     ┆ .fr ┆ .sk ┆ .sv ┆     ┆     ┆     ┆ dat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ i64 ┆     ┆     ┆ str ┆ str ┆ str ┆ fau ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆     ┆ lt  ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 848 ┆ htt ┆ 62  ┆ C   ┆ R   ┆ 72  ┆ 190 ┆ 183 ┆ 86  ┆ 200 ┆ CAN ┆ Owe ┆ Bec ┆ Por ┆ Ont ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Owe ┆ MTL ┆ 202 ┆ NHL │
│ 342 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-0 ┆     ┆ n   ┆ k   ┆ t   ┆ ari ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ n   ┆     ┆ 5-0 ┆ API │
│ 4   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆     ┆     ┆ Hop ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Bec ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k   ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ 73  ┆ C   ┆ L   ┆ 73  ┆ 223 ┆ 185 ┆ 101 ┆ 199 ┆ CAN ┆ Luc ┆ Con ┆ Geo ┆ Ont ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Luc ┆ MTL ┆ 202 ┆ NHL │
│ 354 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆     ┆ as  ┆ dot ┆ rge ┆ ari ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ as  ┆     ┆ 5-0 ┆ API │
│ 9   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-1 ┆     ┆     ┆ ta  ┆ tow ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Con ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dot ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ta  ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ 76  ┆ C   ┆ L   ┆ 71  ┆ 183 ┆ 180 ┆ 83  ┆ 200 ┆ CAN ┆ Jar ┆ Dav ┆ Edm ┆ Alb ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Jar ┆ MTL ┆ 202 ┆ NHL │
│ 372 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆ ed  ┆ ids ┆ ont ┆ ert ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ed  ┆     ┆ 5-0 ┆ API │
│ 8   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7-0 ┆     ┆     ┆ on  ┆ on  ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Dav ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ids ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ nul ┆ C   ┆ L   ┆ 71  ┆ 179 ┆ 180 ┆ 81  ┆ 200 ┆ SWE ┆ Fil ┆ Eri ┆ Lju ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Fil ┆ MTL ┆ 202 ┆ NHL │
│ 444 ┆ ps: ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-1 ┆     ┆ ip  ┆ kss ┆ ngb ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ip  ┆     ┆ 5-0 ┆ API │
│ 8   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆ on  ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Eri ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kss ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ 57  ┆ C   ┆ L   ┆ 69  ┆ 175 ┆ 175 ┆ 79  ┆ 200 ┆ USA ┆ Sea ┆ Far ┆ Mil ┆ Mas ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Sea ┆ MTL ┆ 202 ┆ NHL │
│ 208 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-1 ┆     ┆ n   ┆ rel ┆ for ┆ sac ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ n   ┆     ┆ 5-0 ┆ API │
│ 1   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-0 ┆     ┆     ┆ l   ┆ d   ┆ hus ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Far ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆     ┆     ┆     ┆ ett ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rel ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l   ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 848 ┆ htt ┆ 75  ┆ G   ┆ L   ┆ 76  ┆ 215 ┆ 193 ┆ 98  ┆ 200 ┆ CZE ┆ Jak ┆ Dob ┆ Ost ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Jak ┆ MTL ┆ 202 ┆ NHL │
│ 248 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-0 ┆     ┆ ub  ┆ es  ┆ rav ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ ub  ┆     ┆ 5-0 ┆ API │
│ 7   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5-2 ┆     ┆     ┆     ┆ a   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Dob ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ es  ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ nul ┆ G   ┆ L   ┆ 73  ┆ 223 ┆ 185 ┆ 101 ┆ 200 ┆ USA ┆ Jac ┆ Fow ┆ Mel ┆ Flo ┆ nul ┆ nul ┆ nul ┆ nul ┆ Flo ┆ nul ┆ nul ┆ nul ┆ Jac ┆ MTL ┆ 202 ┆ NHL │
│ 417 ┆ ps: ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-1 ┆     ┆ ob  ┆ ler ┆ bou ┆ rid ┆ l   ┆ l   ┆ l   ┆ l   ┆ rid ┆ l   ┆ l   ┆ l   ┆ ob  ┆     ┆ 5-0 ┆ API │
│ 0   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-2 ┆     ┆     ┆     ┆ rne ┆ a   ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     ┆ Fow ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ler ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ nul ┆ G   ┆ L   ┆ 75  ┆ 190 ┆ 191 ┆ 86  ┆ 200 ┆ CAN ┆ Que ┆ Mil ┆ Mon ┆ Que ┆ nul ┆ nul ┆ nul ┆ nul ┆ Qué ┆ nul ┆ nul ┆ nul ┆ Que ┆ MTL ┆ 202 ┆ NHL │
│ 441 ┆ ps: ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-1 ┆     ┆ nti ┆ ler ┆ tré ┆ bec ┆ l   ┆ l   ┆ l   ┆ l   ┆ bec ┆ l   ┆ l   ┆ l   ┆ nti ┆     ┆ 5-0 ┆ API │
│ 6   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-2 ┆     ┆ n   ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Mil ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ler ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ nul ┆ G   ┆ L   ┆ 72  ┆ 159 ┆ 183 ┆ 72  ┆ 200 ┆ RUS ┆ Yev ┆ Vol ┆ Kha ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Yev ┆ MTL ┆ 202 ┆ NHL │
│ 442 ┆ ps: ┆ l   ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5-0 ┆     ┆ gen ┆ okh ┆ nty ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ gen ┆     ┆ 5-0 ┆ API │
│ 4   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-0 ┆     ┆ i   ┆ in  ┆ -Ma ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i   ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆     ┆     ┆     ┆ nsi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Vol ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ysk ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ okh ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ in  ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 813 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ 39  ┆ G   ┆ L   ┆ 78  ┆ 198 ┆ 198 ┆ 90  ┆ 200 ┆ CAN ┆ Joe ┆ Vrb ┆ Ham ┆ Ont ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ Joe ┆ MTL ┆ 202 ┆ NHL │
│ 266 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-1 ┆     ┆     ┆ eti ┆ ilt ┆ ari ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ Vrb ┆     ┆ 5-0 ┆ API │
│ 9   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0-2 ┆     ┆     ┆ c   ┆ on  ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 48. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 444 ┆     │

In [18]:
scrape.scrapeTeamStats("MTL", "20242025", 2, False)

shape: (27, 28)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ pla ┆ hea ┆ pos ┆ gam ┆ goa ┆ ass ┆ poi ┆ plu ┆ pen ┆ pow ┆ sho ┆ gam ┆ ove ┆ sho ┆ sho ┆ avg ┆ avg ┆ fac ┆ fir ┆ las ┆ las ┆ las ┆ ful ┆ tea ┆ sea ┆ ses ┆ met ┆ met │
│ yer ┆ dsh ┆ iti ┆ esP ┆ ls  ┆ ist ┆ nts ┆ sMi ┆ alt ┆ erP ┆ rth ┆ eWi ┆ rti ┆ ts  ┆ oti ┆ Tim ┆ Shi ┆ eof ┆ stN ┆ tNa ┆ tNa ┆ tNa ┆ lNa ┆ m   ┆ son ┆ sio ┆ a_d ┆ a_s │
│ Id  ┆ ot  ┆ onC ┆ lay ┆ --- ┆ s   ┆ --- ┆ nus ┆ yMi ┆ lay ┆ and ┆ nni ┆ meG ┆ --- ┆ ngP ┆ eOn ┆ fts ┆ fWi ┆ ame ┆ me. ┆ me. ┆ me. ┆ me  ┆ --- ┆ --- ┆ nId ┆ ate ┆ our │
│ --- ┆ --- ┆ ode ┆ ed  ┆ i64 ┆ --- ┆ i64 ┆ --- ┆ nut ┆ Goa ┆ edG ┆ ngG ┆ oal ┆ i64 ┆ ctg ┆ Ice ┆ Per ┆ nPc ┆ .de ┆ def ┆ cs  ┆ sk  ┆ --- ┆ str ┆ str ┆ --- ┆ tim ┆ ce  │
│ i64 ┆ str ┆ --- ┆ --- ┆     ┆ i64 ┆     ┆ i64 ┆ es  ┆ ls  ┆ oal ┆ oal ┆ s   ┆     ┆ --- ┆ Per ┆ Gam ┆ tg  ┆ fau ┆ aul ┆ --- ┆ --- ┆ str ┆     ┆     ┆ i32 ┆ e   ┆ --- │
│     ┆     ┆ str ┆ i64 ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ s   ┆ s   ┆ --- ┆     ┆ f64 ┆ Gam ┆ e   ┆ --- ┆ lt  ┆ t   ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ --- ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ i64 ┆     ┆     ┆ e   ┆ --- ┆ f64 ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ dat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆ i64 ┆     ┆     ┆     ┆ --- ┆ f64 ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 847 ┆ htt ┆ D   ┆ 50  ┆ 1   ┆ 10  ┆ 11  ┆ -7  ┆ 26  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 35  ┆ 0.0 ┆ 106 ┆ 20. ┆ 0.0 ┆ Dav ┆ Sav ┆ nul ┆ nul ┆ Dav ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 523 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 285 ┆ 5.5 ┆ 84  ┆     ┆ id  ┆ ard ┆ l   ┆ l   ┆ id  ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 3   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 71  ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sav ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ard ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 847 ┆ htt ┆ R   ┆ 56  ┆ 14  ┆ 9   ┆ 23  ┆ -13 ┆ 25  ┆ 5   ┆ 0   ┆ 1   ┆ 0   ┆ 104 ┆ 0.1 ┆ 822 ┆ 17. ┆ 0.0 ┆ Bre ┆ Gal ┆ nul ┆ nul ┆ Bre ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 584 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 346 ┆ .39 ┆ 589 ┆     ┆ nda ┆ lag ┆ l   ┆ l   ┆ nda ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 8   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 15  ┆ 29  ┆ 3   ┆     ┆ n   ┆ her ┆     ┆     ┆ n   ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Gal ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ lag ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ her ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 847 ┆ htt ┆ R   ┆ 56  ┆ 10  ┆ 14  ┆ 24  ┆ 1   ┆ 16  ┆ 0   ┆ 3   ┆ 1   ┆ 0   ┆ 83  ┆ 0.1 ┆ 877 ┆ 17. ┆ 0.1 ┆ Joe ┆ Arm ┆ nul ┆ nul ┆ Joe ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 646 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 204 ┆ .16 ┆ 785 ┆ 818 ┆ l   ┆ ia  ┆ l   ┆ l   ┆ l   ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 9   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 82  ┆ 07  ┆ 7   ┆ 18  ┆     ┆     ┆     ┆     ┆ Arm ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ia  ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 847 ┆ htt ┆ D   ┆ 54  ┆ 4   ┆ 21  ┆ 25  ┆ -9  ┆ 43  ┆ 1   ┆ 0   ┆ 0   ┆ 0   ┆ 104 ┆ 0.0 ┆ 147 ┆ 25. ┆ 0.0 ┆ Mik ┆ Mat ┆ nul ┆ nul ┆ Mik ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 687 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 384 ┆ 7.9 ┆ 037 ┆     ┆ e   ┆ hes ┆ l   ┆ l   ┆ e   ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 5   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 62  ┆ 444 ┆     ┆     ┆     ┆ on  ┆     ┆     ┆ Mat ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ hes ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 847 ┆ htt ┆ R   ┆ 56  ┆ 8   ┆ 10  ┆ 18  ┆ -11 ┆ 56  ┆ 0   ┆ 1   ┆ 0   ┆ 0   ┆ 79  ┆ 0.1 ┆ 849 ┆ 18. ┆ 0.6 ┆ Jos ┆ And ┆ nul ┆ nul ┆ Jos ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 698 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 012 ┆ .69 ┆ 678 ┆ 176 ┆ h   ┆ ers ┆ l   ┆ l   ┆ h   ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 1   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 66  ┆ 64  ┆ 6   ┆ 47  ┆     ┆ on  ┆     ┆     ┆ And ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ers ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ on  ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 848 ┆ htt ┆ D   ┆ 53  ┆ 1   ┆ 4   ┆ 5   ┆ -8  ┆ 83  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 58  ┆ 0.0 ┆ 907 ┆ 18. ┆ 0.0 ┆ Arb ┆ Xhe ┆ nul ┆ nul ┆ Arb ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 296 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 172 ┆ .56 ┆ 169 ┆     ┆ er  ┆ kaj ┆ l   ┆ l   ┆ er  ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 4   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 41  ┆ 6   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆ Xhe ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kaj ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ C   ┆ 6   ┆ 0   ┆ 0   ┆ 0   ┆ -2  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 6   ┆ 0.0 ┆ 585 ┆ 12. ┆ 0.5 ┆ Owe ┆ Bec ┆ nul ┆ nul ┆ Owe ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 342 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .33 ┆ 333 ┆ 238 ┆ n   ┆ k   ┆ l   ┆ l   ┆ n   ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 4   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 33  ┆ 3   ┆ 1   ┆     ┆     ┆     ┆     ┆ Bec ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ k   ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ D   ┆ 56  ┆ 3   ┆ 38  ┆ 41  ┆ -20 ┆ 32  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 65  ┆ 0.0 ┆ 135 ┆ 23. ┆ 0.0 ┆ Lan ┆ Hut ┆ nul ┆ nul ┆ Lan ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 345 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 461 ┆ 0.6 ┆ 089 ┆     ┆ e   ┆ son ┆ l   ┆ l   ┆ e   ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 7   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 54  ┆ 25  ┆ 3   ┆     ┆     ┆     ┆     ┆     ┆ Hut ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ son ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ L   ┆ 53  ┆ 8   ┆ 22  ┆ 30  ┆ -10 ┆ 20  ┆ 2   ┆ 0   ┆ 0   ┆ 0   ┆ 71  ┆ 0.1 ┆ 101 ┆ 18. ┆ 0.4 ┆ Jur ┆ Sla ┆ Sla ┆ Sla ┆ Jur ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 351 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 126 ┆ 1.9 ┆ 075 ┆ 166 ┆ aj  ┆ fko ┆ fko ┆ fko ┆ aj  ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 5   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 76  ┆ 623 ┆ 5   ┆ 67  ┆     ┆ vsk ┆ vsk ┆ vsk ┆ Sla ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆ ý   ┆ ý   ┆ fko ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ vsk ┆     ┆     ┆     ┆ 16: ┆     │
│     ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆ 46: ┆     │
│     ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 55. ┆     │
│     ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 061 ┆     │
│     ┆ mug ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 429 ┆     │
│     ┆ s/n ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 848 ┆ htt ┆ L   ┆ 7   ┆ 1   ┆ 0   ┆ 1   ┆ -2  ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 0   ┆ 5   ┆ 0.2 ┆ 492 ┆ 11. ┆ 0.5 ┆ Luc ┆ Con ┆ nul ┆ nul ┆ Luc ┆ MTL ┆ 202 ┆ 2   ┆ 202 ┆ NHL │
│ 354 ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .14 ┆ 714 ┆ 862 ┆ as  ┆ dot ┆ l   ┆ l   ┆ as  ┆     ┆ 420 ┆     ┆ 5-0 ┆ API │
│ 9   ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 29  ┆ 3   ┆ 07  ┆     ┆ ta  ┆     ┆     ┆ Con ┆     ┆ 25  ┆     ┆ 2-1 ┆     │
│     ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ dot ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ta  ┆     ┆     ┆     ┆ 16: ┆     │

In [10]:
scrape.scrapeActiveTeams()

shape: (32, 9)
┌────────┬────────┬───────────┬───────────┬───────────┬───────────┬──────────┬──────────┬──────────┐
│ teamId ┆ abbrev ┆ name      ┆ commonNam ┆ placeName ┆ logo      ┆ darkLogo ┆ meta_dat ┆ meta_sou │
│ ---    ┆ ---    ┆ ---       ┆ e         ┆ WithPrepo ┆ ---       ┆ ---      ┆ etime    ┆ rce      │
│ i64    ┆ str    ┆ str       ┆ ---       ┆ sition    ┆ str       ┆ str      ┆ ---      ┆ ---      │
│        ┆        ┆           ┆ str       ┆ ---       ┆           ┆          ┆ datetime ┆ str      │
│        ┆        ┆           ┆           ┆ str       ┆           ┆          ┆ [μs]     ┆          │
╞════════╪════════╪═══════════╪═══════════╪═══════════╪═══════════╪══════════╪══════════╪══════════╡
│ 1      ┆ NJD    ┆ New       ┆ Devils    ┆ New       ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Jersey    ┆           ┆ Jersey    ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆ Devils    ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 2      ┆ NYI    ┆ New York  ┆ Islanders ┆ New York  ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Islanders ┆           ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆           ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 3      ┆ NYR    ┆ New York  ┆ Rangers   ┆ New York  ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Rangers   ┆           ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆           ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 4      ┆ PHI    ┆ Philadelp ┆ Flyers    ┆ Philadelp ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ hia       ┆           ┆ hia       ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆ Flyers    ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 5      ┆ PIT    ┆ Pittsburg ┆ Penguins  ┆ Pittsburg ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ h         ┆           ┆ h         ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆ Penguins  ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ …      ┆ …      ┆ …         ┆ …         ┆ …         ┆ …         ┆ …        ┆ …        ┆ …        │
│ 30     ┆ MIN    ┆ Minnesota ┆ Wild      ┆ Minnesota ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Wild      ┆           ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆           ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 52     ┆ WPG    ┆ Winnipeg  ┆ Jets      ┆ Winnipeg  ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Jets      ┆           ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆           ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 54     ┆ VGK    ┆ Vegas     ┆ Golden    ┆ Vegas     ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Golden    ┆ Knights   ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆ Knights   ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 55     ┆ SEA    ┆ Seattle   ┆ Kraken    ┆ Seattle   ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Kraken    ┆           ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆           ┆           ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
│ 59     ┆ UTA    ┆ Utah      ┆ Utah      ┆ Utah      ┆ https://a ┆ https:// ┆ 2025-02- ┆ NHL API  │
│        ┆        ┆ Hockey    ┆ Hockey    ┆           ┆ ssets.nhl ┆ assets.n ┆ 19 14:49 ┆          │
│        ┆        ┆ Club      ┆ Club      ┆           ┆ e.com/log ┆ hle.com/ ┆ :24.8748 ┆          │
│        ┆        ┆           ┆           ┆           ┆ os/…      ┆ logos/…  ┆ 96       ┆          │
└────────┴────────┴───────────┴───────────┴───────────┴───────────┴──────────┴──────────┴──────────┘

In [28]:
scrape.scrapeSchedule("MTL", "20242025")

shape: (88, 81)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ id  ┆ sea ┆ gam ┆ gam ┆ neu ┆ sta ┆ eas ┆ ven ┆ ven ┆ gam ┆ gam ┆ tvB ┆ thr ┆ con ┆ gam ┆ ven ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ awa ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ hom ┆ per ┆ per ┆ gam ┆ win ┆ win ┆ win ┆ win ┆ win ┆ win ┆ thr ┆ awa ┆ ven ┆ hom ┆ hom ┆ hom ┆ win ┆ win ┆ win ┆ hom ┆ con ┆ win ┆ hom ┆ hom ┆ awa ┆ awa ┆ awa ┆ awa ┆ win ┆ win ┆ win ┆ win ┆ ven ┆ tic ┆ tic ┆ awa ┆ hom ┆ awa ┆ awa ┆ hom ┆ hom ┆ tea ┆ ses ┆ met ┆ met │
│ --- ┆ son ┆ eTy ┆ eDa ┆ tra ┆ rtT ┆ ter ┆ ueU ┆ ueT ┆ eSt ┆ eSc ┆ roa ┆ eeM ┆ den ┆ eCe ┆ ue. ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ eTe ┆ iod ┆ iod ┆ eOu ┆ nin ┆ nin ┆ nin ┆ nin ┆ nin ┆ nin ┆ eeM ┆ yTe ┆ ue. ┆ eTe ┆ eTe ┆ eTe ┆ nin ┆ nin ┆ nin ┆ eTe ┆ den ┆ nin ┆ eTe ┆ eTe ┆ yTe ┆ yTe ┆ yTe ┆ yTe ┆ nin ┆ nin ┆ nin ┆ nin ┆ ue. ┆ ket ┆ ket ┆ yTe ┆ eTe ┆ yTe ┆ yTe ┆ eTe ┆ eTe ┆ m   ┆ sio ┆ a_d ┆ a_s │
│ i64 ┆ --- ┆ pe  ┆ te  ┆ lSi ┆ ime ┆ nUT ┆ TCO ┆ ime ┆ ate ┆ hed ┆ dca ┆ inR ┆ sed ┆ nte ┆ def ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ Des ┆ Des ┆ tco ┆ gGo ┆ gGo ┆ gGo ┆ gGo ┆ gGo ┆ gGo ┆ inR ┆ am. ┆ fr  ┆ am. ┆ am. ┆ am. ┆ gGo ┆ gGo ┆ gGo ┆ am. ┆ sed ┆ gGo ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ gGo ┆ gGo ┆ gGo ┆ gGo ┆ es  ┆ sLi ┆ sLi ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ am. ┆ --- ┆ n   ┆ ate ┆ our │
│     ┆ str ┆ --- ┆ --- ┆ te  ┆ UTC ┆ COf ┆ ffs ┆ zon ┆ --- ┆ ule ┆ sts ┆ eca ┆ Gam ┆ rLi ┆ aul ┆ id  ┆ com ┆ pla ┆ pla ┆ pla ┆ pla ┆ abb ┆ log ┆ dar ┆ awa ┆ sco ┆ id  ┆ com ┆ pla ┆ pla ┆ pla ┆ abb ┆ log ┆ dar ┆ hom ┆ sco ┆ cri ┆ cri ┆ me. ┆ ali ┆ ali ┆ ali ┆ alS ┆ alS ┆ alS ┆ eca ┆ com ┆ --- ┆ com ┆ air ┆ air ┆ ali ┆ ali ┆ ali ┆ pla ┆ Gam ┆ ali ┆ hot ┆ hot ┆ air ┆ air ┆ hot ┆ hot ┆ alS ┆ alS ┆ alS ┆ alS ┆ --- ┆ nk  ┆ nkF ┆ rad ┆ rad ┆ pro ┆ pro ┆ pro ┆ pro ┆ str ┆ --- ┆ tim ┆ ce  │
│     ┆     ┆ i64 ┆ dat ┆ --- ┆ --- ┆ fse ┆ et  ┆ e   ┆ str ┆ Sta ┆ --- ┆ pFr ┆ eFr ┆ nk  ┆ t   ┆ --- ┆ mon ┆ ceN ┆ ceN ┆ ceN ┆ ceN ┆ rev ┆ o   ┆ kLo ┆ ySp ┆ re  ┆ --- ┆ mon ┆ ceN ┆ ceN ┆ ceN ┆ rev ┆ o   ┆ kLo ┆ eSp ┆ re  ┆ pto ┆ pto ┆ las ┆ e.p ┆ e.f ┆ e.l ┆ cor ┆ cor ┆ cor ┆ p   ┆ mon ┆ str ┆ mon ┆ lin ┆ lin ┆ e.l ┆ e.l ┆ e.l ┆ ceN ┆ e   ┆ e.l ┆ elL ┆ elD ┆ lin ┆ lin ┆ elL ┆ elD ┆ cor ┆ cor ┆ cor ┆ cor ┆ str ┆ --- ┆ r   ┆ ioL ┆ ioL ┆ moL ┆ moD ┆ moL ┆ moD ┆     ┆ str ┆ e   ┆ --- │
│     ┆     ┆     ┆ e   ┆ boo ┆ str ┆ t   ┆ --- ┆ --- ┆     ┆ te  ┆ lis ┆ --- ┆ --- ┆ --- ┆ --- ┆ i64 ┆ Nam ┆ ame ┆ ame ┆ ame ┆ ame ┆ --- ┆ --- ┆ go  ┆ lit ┆ --- ┆ i64 ┆ Nam ┆ ame ┆ ame ┆ ame ┆ --- ┆ --- ┆ go  ┆ lit ┆ --- ┆ r.p ┆ r.m ┆ tPe ┆ lay ┆ irs ┆ ast ┆ er. ┆ er. ┆ er. ┆ --- ┆ Nam ┆     ┆ Nam ┆ eLi ┆ eDe ┆ ast ┆ ast ┆ ast ┆ ame ┆ --- ┆ ast ┆ ink ┆ esc ┆ eLi ┆ eDe ┆ ink ┆ esc ┆ er. ┆ er. ┆ er. ┆ er. ┆     ┆ str ┆ --- ┆ ink ┆ ink ┆ ink ┆ esc ┆ ink ┆ esc ┆     ┆     ┆ --- ┆ str │
│     ┆     ┆     ┆     ┆ l   ┆     ┆ --- ┆ str ┆ str ┆     ┆ --- ┆ t[s ┆ str ┆ str ┆ str ┆ str ┆     ┆ e.d ┆ .de ┆ .fr ┆ Wit ┆ Wit ┆ str ┆ str ┆ --- ┆ Squ ┆ i64 ┆     ┆ e.d ┆ .de ┆ Wit ┆ Wit ┆ str ┆ str ┆ --- ┆ Squ ┆ i64 ┆ eri ┆ axR ┆ rio ┆ erI ┆ tIn ┆ Nam ┆ pla ┆ fir ┆ las ┆ str ┆ e.f ┆     ┆ e.f ┆ nk  ┆ sc  ┆ Nam ┆ Nam ┆ Nam ┆ .fr ┆ str ┆ Nam ┆ --- ┆ --- ┆ nk  ┆ sc  ┆ --- ┆ --- ┆ las ┆ las ┆ las ┆ las ┆     ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ dat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆ str ┆ tru ┆     ┆     ┆     ┆     ┆     ┆ efa ┆ fau ┆ --- ┆ hPr ┆ hPr ┆     ┆     ┆ str ┆ ad  ┆     ┆     ┆ efa ┆ fau ┆ hPr ┆ hPr ┆     ┆     ┆ str ┆ ad  ┆     ┆ odT ┆ egu ┆ dTy ┆ d   ┆ iti ┆ e.d ┆ yer ┆ stI ┆ tNa ┆     ┆ r   ┆     ┆ r   ┆ --- ┆ --- ┆ e.c ┆ e.f ┆ e.s ┆ --- ┆     ┆ e.s ┆ str ┆ str ┆ --- ┆ --- ┆ str ┆ str ┆ tNa ┆ tNa ┆ tNa ┆ tNa ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆ str ┆ str ┆ str ┆     ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ct[ ┆     ┆     ┆     ┆     ┆     ┆ ult ┆ lt  ┆ str ┆ epo ┆ epo ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ ult ┆ lt  ┆ epo ┆ epo ┆     ┆     ┆     ┆ --- ┆     ┆ ype ┆ lat ┆ pe  ┆ --- ┆ al. ┆ efa ┆ Id  ┆ nit ┆ me. ┆     ┆ --- ┆     ┆ --- ┆ str ┆ str ┆ s   ┆ i   ┆ k   ┆ str ┆     ┆ v   ┆     ┆     ┆ str ┆ str ┆     ┆     ┆ me. ┆ me. ┆ me. ┆ me. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5]] ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆ sit ┆ sit ┆     ┆     ┆     ┆ boo ┆     ┆     ┆ --- ┆ --- ┆ sit ┆ sit ┆     ┆     ┆     ┆ boo ┆     ┆ --- ┆ ion ┆ --- ┆ i64 ┆ def ┆ ult ┆ --- ┆ ial ┆ def ┆     ┆ str ┆     ┆ str ┆     ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ cs  ┆ fi  ┆ sk  ┆ sv  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆ l   ┆     ┆     ┆ str ┆ str ┆ …   ┆ …   ┆     ┆     ┆     ┆ l   ┆     ┆ str ┆ …   ┆ str ┆     ┆ …   ┆ --- ┆ i64 ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆ --- ┆ str ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆     ┆ str ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 202 ┆ 1   ┆ 202 ┆ fal ┆ 202 ┆ -04 ┆ -04 ┆ Ame ┆ FIN ┆ OK  ┆ [{3 ┆ /fr ┆ /fr ┆ /ga ┆ Cen ┆ 4   ┆ Fly ┆ Phi ┆ Phi ┆ Phi ┆ de  ┆ PHI ┆ htt ┆ htt ┆ fal ┆ 0   ┆ 8   ┆ Can ┆ Mon ┆ Mon ┆ de  ┆ MTL ┆ htt ┆ htt ┆ fal ┆ 5   ┆ REG ┆ 3   ┆ REG ┆ 848 ┆ C.  ┆ Pri ┆ 848 ┆ L.  ┆ Tuc ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ MTL ┆ PRE ┆ 202 ┆ NHL │
│ 401 ┆ 420 ┆     ┆ 4-0 ┆ se  ┆ 4-0 ┆ :00 ┆ :00 ┆ ric ┆ AL  ┆     ┆ 3," ┆ /vi ┆ /vi ┆ mec ┆ tre ┆     ┆ ers ┆ lad ┆ lad ┆ lad ┆ Phi ┆     ┆ ps: ┆ ps: ┆ se  ┆     ┆     ┆ adi ┆ tré ┆ tré ┆ Mon ┆     ┆ ps: ┆ ps: ┆ se  ┆     ┆     ┆     ┆     ┆ 005 ┆     ┆ mea ┆ 213 ┆     ┆ h   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ SEA ┆ 5-0 ┆ API │
│ 001 ┆ 25  ┆     ┆ 9-2 ┆     ┆ 9-2 ┆     ┆     ┆ a/M ┆     ┆     ┆ H", ┆ deo ┆ deo ┆ ent ┆ Bel ┆     ┆     ┆ elp ┆ elp ┆ elp ┆ lad ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆ ens ┆ al  ┆ al  ┆ tré ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆ u   ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SON ┆ 2-1 ┆     │
│ 5   ┆     ┆     ┆ 3   ┆     ┆ 3T2 ┆     ┆     ┆ ont ┆     ┆     ┆ "CA ┆ /re ┆ /co ┆ er/ ┆ l   ┆     ┆     ┆ hia ┆ hie ┆ hia ┆ elp ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ 3:0 ┆     ┆     ┆ rea ┆     ┆     ┆ "," ┆ cap ┆ nde ┆ phi ┆     ┆     ┆     ┆     ┆     ┆     ┆ hie ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆     ┆     ┆     ┆     ┆ 0:0 ┆     ┆     ┆ l   ┆     ┆     ┆ RDS ┆ -fl ┆ nse ┆ -vs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆ 0Z  ┆     ┆     ┆     ┆     ┆     ┆ ",1 ┆ yer ┆ d-g ┆ -mt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 32} ┆ s-a ┆ ame ┆ l/2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 722 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ]   ┆ t-c ┆ -fl ┆ 024 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 875 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ana ┆ yer ┆ /09 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 1   ┆ 202 ┆ fal ┆ 202 ┆ -04 ┆ -04 ┆ Ame ┆ FIN ┆ OK  ┆ [{3 ┆ /fr ┆ nul ┆ /ga ┆ Cen ┆ 1   ┆ Dev ┆ New ┆ nul ┆ New ┆ du  ┆ NJD ┆ htt ┆ htt ┆ fal ┆ 0   ┆ 8   ┆ Can ┆ Mon ┆ Mon ┆ de  ┆ MTL ┆ htt ┆ htt ┆ fal ┆ 3   ┆ REG ┆ 3   ┆ REG ┆ 847 ┆ S.  ┆ Mon ┆ 847 ┆ M.  ┆ Pez ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ MTL ┆ PRE ┆ 202 ┆ NHL │
│ 401 ┆ 420 ┆     ┆ 4-0 ┆ se  ┆ 4-0 ┆ :00 ┆ :00 ┆ ric ┆ AL  ┆     ┆ 3," ┆ /vi ┆ l   ┆ mec ┆ tre ┆     ┆ ils ┆ Jer ┆ l   ┆ Jer ┆ New ┆     ┆ ps: ┆ ps: ┆ se  ┆     ┆     ┆ adi ┆ tré ┆ tré ┆ Mon ┆     ┆ ps: ┆ ps: ┆ se  ┆     ┆     ┆     ┆     ┆ 847 ┆     ┆ tem ┆ 954 ┆     ┆ zet ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ SEA ┆ 5-0 ┆ API │
│ 002 ┆ 25  ┆     ┆ 9-2 ┆     ┆ 9-2 ┆     ┆     ┆ a/M ┆     ┆     ┆ H", ┆ deo ┆     ┆ ent ┆ Bel ┆     ┆     ┆ sey ┆     ┆ sey ┆ Jer ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆ ens ┆ al  ┆ al  ┆ tré ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ bea ┆ 3   ┆     ┆ ta  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SON ┆ 2-1 ┆     │
│ 2   ┆     ┆     ┆ 4   ┆     ┆ 4T2 ┆     ┆     ┆ ont ┆     ┆     ┆ "CA ┆ /re ┆     ┆ er/ ┆ l   ┆     ┆     ┆     ┆     ┆     ┆ sey ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ult ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ 3:0 ┆     ┆     ┆ rea ┆     ┆     ┆ "," ┆ cap ┆     ┆ njd ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 17: ┆     │
│     ┆     ┆     ┆     ┆     ┆ 0:0 ┆     ┆     ┆ l   ┆     ┆     ┆ RDS ┆ -de ┆     ┆ -vs ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 18: ┆     │
│     ┆     ┆     ┆     ┆     ┆ 0Z  ┆     ┆     ┆     ┆     ┆     ┆ ",1 ┆ vil ┆     ┆ -mt ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 06. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 32} ┆ s-a ┆     ┆ l/2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 722 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ]   ┆ t-c ┆     ┆ 024 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 875 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ana ┆     ┆ /09 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 1   ┆ 202 ┆ fal ┆ 202 ┆ -04 ┆ -04 ┆ Ame ┆ FIN ┆ OK  ┆ [{2 ┆ /fr ┆ /fr ┆ /ga ┆ Sco ┆ 8   ┆ Can ┆ Mon ┆ nul ┆ Mon ┆ de  ┆ MTL ┆ htt ┆ htt ┆ fal ┆ 1   ┆ 10  ┆ Map ┆ Tor ┆ Tor ┆ de  ┆ TOR ┆ htt ┆ htt ┆ fal ┆ 2   ┆ REG ┆ 3   ┆ REG ┆ 847 ┆ A.  ┆ Sto ┆ 848 ┆ N.  ┆ Rob ┆ /vi ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ MTL ┆ PRE ┆ 202 ┆ NHL │
│ 401 ┆ 420 ┆     ┆ 4-0 ┆ se  ┆ 4-0 ┆ :00 ┆ :00 ┆ ric ┆ AL  ┆     ┆ 82, ┆ /vi ┆ /vi ┆ mec ┆ tia ┆     ┆ adi ┆ tré ┆ l   ┆ tré ┆ Mon ┆     ┆ ps: ┆ ps: ┆ se  ┆     ┆     ┆ le  ┆ ont ┆ ont ┆ Tor ┆     ┆ ps: ┆ ps: ┆ se  ┆     ┆     ┆     ┆     ┆ 693 ┆     ┆ lar ┆ 158 ┆     ┆ ert ┆ deo ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆     ┆ SEA ┆ 5-0 ┆ API │
│ 003 ┆ 25  ┆     ┆ 9-2 ┆     ┆ 9-2 ┆     ┆     ┆ a/T ┆     ┆     ┆ "N" ┆ deo ┆ deo ┆ ent ┆ ban ┆     ┆ ens ┆ al  ┆     ┆ al  ┆ tré ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆ Lea ┆ o   ┆ o   ┆ ont ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ z   ┆ 2   ┆     ┆ son ┆ /re ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ SON ┆ 2-1 ┆     │

In [11]:
scrape.scrapeDraft(2024)

shape: (225, 26)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ rou ┆ pic ┆ ove ┆ tea ┆ tea ┆ tea ┆ tea ┆ tea ┆ pos ┆ cou ┆ hei ┆ wei ┆ ama ┆ ama ┆ tea ┆ tea ┆ tea ┆ tea ┆ tea ┆ dis ┆ fir ┆ las ┆ tea ┆ yea ┆ met ┆ met │
│ nd  ┆ kIn ┆ ral ┆ mId ┆ mAb ┆ mLo ┆ mLo ┆ mPi ┆ iti ┆ ntr ┆ ght ┆ ght ┆ teu ┆ teu ┆ mNa ┆ mNa ┆ mCo ┆ mPl ┆ mPl ┆ pla ┆ stN ┆ tNa ┆ mCo ┆ r   ┆ a_d ┆ a_s │
│ --- ┆ Rou ┆ lPi ┆ --- ┆ bre ┆ goL ┆ goD ┆ ckH ┆ onC ┆ yCo ┆ --- ┆ --- ┆ rLe ┆ rCl ┆ me. ┆ me. ┆ mmo ┆ ace ┆ ace ┆ yAb ┆ ame ┆ me. ┆ mmo ┆ --- ┆ ate ┆ our │
│ i64 ┆ nd  ┆ ck  ┆ i64 ┆ v   ┆ igh ┆ ark ┆ ist ┆ ode ┆ de  ┆ i64 ┆ i64 ┆ agu ┆ ubN ┆ def ┆ fr  ┆ nNa ┆ Nam ┆ Nam ┆ bre ┆ .de ┆ def ┆ nNa ┆ i32 ┆ tim ┆ ce  │
│     ┆ --- ┆ --- ┆     ┆ --- ┆ t   ┆ --- ┆ ory ┆ --- ┆ --- ┆     ┆     ┆ e   ┆ ame ┆ aul ┆ --- ┆ me. ┆ eWi ┆ eWi ┆ v.d ┆ fau ┆ aul ┆ me. ┆     ┆ e   ┆ --- │
│     ┆ i64 ┆ i64 ┆     ┆ str ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆     ┆     ┆ --- ┆ --- ┆ t   ┆ str ┆ def ┆ thP ┆ thP ┆ efa ┆ lt  ┆ t   ┆ fr  ┆     ┆ --- ┆ str │
│     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ --- ┆     ┆ aul ┆ rep ┆ rep ┆ ult ┆ --- ┆ --- ┆ --- ┆     ┆ dat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆ t   ┆ osi ┆ osi ┆ --- ┆ str ┆ str ┆ str ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ tio ┆ tio ┆ str ┆     ┆     ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ n.d ┆ n.f ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 1   ┆ 1   ┆ 1   ┆ 28  ┆ SJS ┆ htt ┆ htt ┆ SJS ┆ C   ┆ CAN ┆ 72  ┆ 197 ┆ H-E ┆ Bos ┆ San ┆ Sha ┆ Sha ┆ San ┆ de  ┆ SJS ┆ Mac ┆ Cel ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ AST ┆ ton ┆ Jos ┆ rks ┆ rks ┆ Jos ┆ San ┆     ┆ kli ┆ ebr ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆ Uni ┆ e   ┆ de  ┆     ┆ e   ┆ Jos ┆     ┆ n   ┆ ini ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ ver ┆ Sha ┆ San ┆     ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆ sit ┆ rks ┆ Jos ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 2   ┆ 2   ┆ 16  ┆ CHI ┆ htt ┆ htt ┆ CHI ┆ D   ┆ BLR ┆ 74  ┆ 205 ┆ BIG ┆ Mic ┆ Chi ┆ Bla ┆ Bla ┆ Chi ┆ de  ┆ CHI ┆ Art ┆ Lev ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ 10  ┆ hig ┆ cag ┆ ckh ┆ ckh ┆ cag ┆ Chi ┆     ┆ yom ┆ shu ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆ an  ┆ o   ┆ awk ┆ awk ┆ o   ┆ cag ┆     ┆     ┆ nov ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sta ┆ Bla ┆ s   ┆ s   ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆ te  ┆ ckh ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆ U.  ┆ awk ┆ Chi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ cag ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 3   ┆ 3   ┆ 24  ┆ ANA ┆ htt ┆ htt ┆ ANA ┆ RW  ┆ CAN ┆ 75  ┆ 182 ┆ OHL ┆ Osh ┆ Ana ┆ Duc ┆ Duc ┆ Ana ┆ d'A ┆ ANA ┆ Bec ┆ Sen ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆ awa ┆ hei ┆ ks  ┆ ks  ┆ hei ┆ nah ┆     ┆ ket ┆ nec ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆ d'A ┆     ┆ m   ┆ eim ┆     ┆ t   ┆ ke  ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Duc ┆ nah ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ks  ┆ eim ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 4   ┆ 4   ┆ 29  ┆ CBJ ┆ htt ┆ htt ┆ CBJ ┆ C   ┆ CAN ┆ 75  ┆ 213 ┆ WHL ┆ Med ┆ Col ┆ Blu ┆ Blu ┆ Col ┆ de  ┆ CBJ ┆ Cay ┆ Lin ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆     ┆ ici ┆ umb ┆ e   ┆ e   ┆ umb ┆ Col ┆     ┆ den ┆ dst ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆     ┆ ne  ┆ us  ┆ Jac ┆ Jac ┆ us  ┆ umb ┆     ┆     ┆ rom ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ Hat ┆ Blu ┆ ket ┆ ket ┆     ┆ us  ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ s   ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Jac ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ket ┆ Col ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ umb ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ us  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 1   ┆ 5   ┆ 5   ┆ 8   ┆ MTL ┆ htt ┆ htt ┆ MTL ┆ RW  ┆ RUS ┆ 73  ┆ 192 ┆ RUS ┆ SKA ┆ Mon ┆ Can ┆ Can ┆ Mon ┆ de  ┆ MTL ┆ Iva ┆ Dem ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ SIA ┆ Sai ┆ tré ┆ adi ┆ adi ┆ tré ┆ Mon ┆     ┆ n   ┆ ido ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆ -JR ┆ nt  ┆ al  ┆ ens ┆ ens ┆ al  ┆ tré ┆     ┆     ┆ v   ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆ .   ┆ Pet ┆ Can ┆ de  ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆ ers ┆ adi ┆ Mon ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆ bur ┆ ens ┆ tré ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆ Jr. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 7   ┆ 28  ┆ 221 ┆ 23  ┆ VAN ┆ htt ┆ htt ┆ VAN ┆ D   ┆ CHE ┆ 75  ┆ 196 ┆ SWI ┆ Fri ┆ Van ┆ Can ┆ Can ┆ Van ┆ de  ┆ VAN ┆ Bas ┆ San ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ SS- ┆ bou ┆ cou ┆ uck ┆ uck ┆ cou ┆ Van ┆     ┆ ile ┆ son ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆ JR. ┆ rg  ┆ ver ┆ s   ┆ s   ┆ ver ┆ cou ┆     ┆     ┆ nen ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ Jr. ┆ Can ┆ de  ┆     ┆     ┆ ver ┆     ┆     ┆ s   ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ uck ┆ Van ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆ cou ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ver ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ 29  ┆ 222 ┆ 25  ┆ DAL ┆ htt ┆ htt ┆ DAL ┆ C   ┆ SWE ┆ 72  ┆ 176 ┆ SWE ┆ Sod ┆ Dal ┆ Sta ┆ Sta ┆ Dal ┆ de  ┆ DAL ┆ Wil ┆ Sam ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆     ┆     ┆     ┆     ┆     ┆ DEN ┆ ert ┆ las ┆ rs  ┆ rs  ┆ las ┆ Dal ┆     ┆ lia ┆ uel ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆     ┆     ┆     ┆     ┆     ┆ -JR ┆ alj ┆ Sta ┆ de  ┆     ┆     ┆ las ┆     ┆ m   ┆ sso ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆ .   ┆ e   ┆ rs  ┆ Dal ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆ Jr. ┆     ┆ las ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ 30  ┆ 223 ┆ 5   ┆ PIT ┆ htt ┆ htt ┆ NYR ┆ D   ┆ CAN ┆ 73  ┆ 198 ┆ OHL ┆ Mis ┆ Pit ┆ Pen ┆ Pen ┆ Pit ┆ de  ┆ PIT ┆ Fin ┆ Har ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆ -PI ┆     ┆     ┆     ┆     ┆     ┆ sis ┆ tsb ┆ gui ┆ gui ┆ tsb ┆ Pit ┆     ┆ n   ┆ din ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆ T   ┆     ┆     ┆     ┆     ┆     ┆ sau ┆ urg ┆ ns  ┆ ns  ┆ urg ┆ tsb ┆     ┆     ┆ g   ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆ ga  ┆ h   ┆ de  ┆     ┆ h   ┆ urg ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Pen ┆ Pit ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gui ┆ tsb ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ns  ┆ urg ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ 31  ┆ 224 ┆ 8   ┆ MTL ┆ htt ┆ htt ┆ EDM ┆ D   ┆ SWE ┆ 74  ┆ 181 ┆ SWE ┆ Ske ┆ Mon ┆ Can ┆ Can ┆ Mon ┆ de  ┆ MTL ┆ Ras ┆ Ber ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆ -MT ┆     ┆     ┆     ┆     ┆ DEN ┆ lle ┆ tré ┆ adi ┆ adi ┆ tré ┆ Mon ┆     ┆ mus ┆ gqv ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆ L   ┆     ┆     ┆     ┆     ┆ -JR ┆ fte ┆ al  ┆ ens ┆ ens ┆ al  ┆ tré ┆     ┆     ┆ ist ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆ .   ┆ a   ┆ Can ┆ de  ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆ Jr. ┆ adi ┆ Mon ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ens ┆ tré ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ al  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 7   ┆ 32  ┆ 225 ┆ 10  ┆ TOR ┆ htt ┆ htt ┆ FLA ┆ D   ┆ CAN ┆ 76  ┆ 194 ┆ WHL ┆ Spo ┆ Tor ┆ Map ┆ Map ┆ Tor ┆ de  ┆ TOR ┆ Nat ┆ May ┆ nul ┆ 202 ┆ 202 ┆ NHL │
│     ┆     ┆     ┆     ┆     ┆ ps: ┆ ps: ┆ -TO ┆     ┆     ┆     ┆     ┆     ┆ kan ┆ ont ┆ le  ┆ le  ┆ ont ┆ Tor ┆     ┆ han ┆ es  ┆ l   ┆ 4   ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆ //a ┆ //a ┆ R   ┆     ┆     ┆     ┆     ┆     ┆ e   ┆ o   ┆ Lea ┆ Lea ┆ o   ┆ ont ┆     ┆     ┆     ┆     ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆ sse ┆ sse ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Map ┆ fs  ┆ fs  ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆ ts. ┆ ts. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ le  ┆ de  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 14: ┆     │
│     ┆     ┆     ┆     ┆     ┆ nhl ┆ nhl ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Lea ┆ Tor ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 00: ┆     │
│     ┆     ┆     ┆     ┆     ┆ e.c ┆ e.c ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ fs  ┆ ont ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 23. ┆     │
│     ┆     ┆     ┆     ┆     ┆ om/ ┆ om/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ o   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 885 ┆     │
│     ┆     ┆     ┆     ┆     ┆ log ┆ log ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 376 ┆     │
│     ┆     ┆     ┆     ┆     ┆ os/ ┆ os/ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆ …   ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [12]:
scrape.scrapeDraftRankings(2025, 2, "polars")

shape: (122, 17)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ las ┆ fir ┆ pos ┆ sho ┆ hei ┆ wei ┆ las ┆ las ┆ bir ┆ bir ┆ bir ┆ mid ┆ bir ┆ cat ┆ cat ┆ met ┆ met │
│ tNa ┆ stN ┆ iti ┆ ots ┆ ght ┆ ght ┆ tAm ┆ tAm ┆ thD ┆ thC ┆ thC ┆ ter ┆ thS ┆ ego ┆ ego ┆ a_d ┆ a_s │
│ me  ┆ ame ┆ onC ┆ Cat ┆ InI ┆ InP ┆ ate ┆ ate ┆ ate ┆ ity ┆ oun ┆ mRa ┆ tat ┆ ry_ ┆ ry_ ┆ ate ┆ our │
│ --- ┆ --- ┆ ode ┆ che ┆ nch ┆ oun ┆ urC ┆ urL ┆ --- ┆ --- ┆ try ┆ nk  ┆ ePr ┆ nam ┆ cod ┆ tim ┆ ce  │
│ str ┆ str ┆ --- ┆ s   ┆ es  ┆ ds  ┆ lub ┆ eag ┆ str ┆ str ┆ --- ┆ --- ┆ ovi ┆ e   ┆ e   ┆ e   ┆ --- │
│     ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆ --- ┆ ue  ┆     ┆     ┆ str ┆ i64 ┆ nce ┆ --- ┆ --- ┆ --- ┆ str │
│     ┆     ┆     ┆ str ┆ i64 ┆ i64 ┆ str ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ i32 ┆ dat ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆ eti ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ me[ ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ Ekl ┆ Vic ┆ RW  ┆ R   ┆ 71  ┆ 161 ┆ DJU ┆ SWE ┆ 200 ┆ Sto ┆ SWE ┆ 1   ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ und ┆ tor ┆     ┆     ┆     ┆     ┆ RGA ┆ DEN ┆ 6-1 ┆ ckh ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆ RDE ┆ -2  ┆ 0-0 ┆ olm ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ N   ┆     ┆ 3   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Fro ┆ Ant ┆ C   ┆ L   ┆ 73  ┆ 198 ┆ DJU ┆ SWE ┆ 200 ┆ Tra ┆ SWE ┆ 2   ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ nde ┆ on  ┆     ┆     ┆     ┆     ┆ RGA ┆ DEN ┆ 7-0 ┆ ngs ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│ ll  ┆     ┆     ┆     ┆     ┆     ┆ RDE ┆ -2  ┆ 5-0 ┆ und ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ N   ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Rya ┆ Iva ┆ C   ┆ L   ┆ 71  ┆ 205 ┆ MUS ┆ USH ┆ 200 ┆ Bal ┆ RUS ┆ 3   ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ bki ┆ n   ┆     ┆     ┆     ┆     ┆ KEG ┆ L   ┆ 7-0 ┆ ako ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│ n   ┆     ┆     ┆     ┆     ┆     ┆ ON  ┆     ┆ 4-2 ┆ vo  ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Gas ┆ Mil ┆ C   ┆ L   ┆ 72  ┆ 185 ┆ MOD ┆ SWE ┆ 200 ┆ Orn ┆ SWE ┆ 4   ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ tri ┆ ton ┆     ┆     ┆     ┆     ┆ O   ┆ DEN ┆ 7-0 ┆ sko ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│ n   ┆     ┆     ┆     ┆     ┆     ┆ JR. ┆ -JR ┆ 6-0 ┆ lds ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆ 2   ┆ vik ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Cih ┆ Voj ┆ LW  ┆ L   ┆ 72  ┆ 175 ┆ KAR ┆ CZE ┆ 200 ┆ Cho ┆ CZE ┆ 5   ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ ar  ┆ tec ┆     ┆     ┆     ┆     ┆ LOV ┆ CHI ┆ 7-0 ┆ mut ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│     ┆ h   ┆     ┆     ┆     ┆     ┆ Y   ┆ A   ┆ 3-2 ┆ ov  ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ VAR ┆     ┆ 9   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ Y   ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ Sjo ┆ Oli ┆ D   ┆ L   ┆ 70  ┆ 173 ┆ LUL ┆ SWE ┆ 200 ┆ Ume ┆ SWE ┆ 118 ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ str ┆ wer ┆     ┆     ┆     ┆     ┆ EA  ┆ DEN ┆ 7-0 ┆ a   ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│ om  ┆     ┆     ┆     ┆     ┆     ┆ JR. ┆ -JR ┆ 4-0 ┆     ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ .   ┆ 8   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Pri ┆ Yeg ┆ RW  ┆ R   ┆ 73  ┆ 196 ┆ SKA ┆ RUS ┆ 200 ┆ Rya ┆ RUS ┆ 119 ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ val ┆ or  ┆     ┆     ┆     ┆     ┆ -YU ┆ SIA ┆ 7-0 ┆ zan ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│ ov  ┆     ┆     ┆     ┆     ┆     ┆ NIO ┆ -JR ┆ 8-2 ┆     ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ R   ┆ .   ┆ 7   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ KRA ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ SNO ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ GOR ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ SK  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Gla ┆ Seb ┆ C   ┆ R   ┆ 73  ┆ 185 ┆ VIT ┆ CZE ┆ 200 ┆ Ost ┆ CZE ┆ 120 ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ s   ┆ ast ┆     ┆     ┆     ┆     ┆ KOV ┆ CHI ┆ 6-1 ┆ rav ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│     ┆ ian ┆     ┆     ┆     ┆     ┆ ICE ┆ A-J ┆ 2-1 ┆ a   ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ JR. ┆ R.  ┆ 5   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Kra ┆ Kal ┆ C   ┆ L   ┆ 73  ┆ 187 ┆ MOR ┆ SWE ┆ 200 ┆ Ors ┆ SWE ┆ 121 ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ tz  ┆ le  ┆     ┆     ┆     ┆     ┆ A   ┆ DEN ┆ 4-0 ┆ a   ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆ -2  ┆ 9-2 ┆     ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
│ Mun ┆ Jer ┆ RW  ┆ L   ┆ 74  ┆ 194 ┆ DAV ┆ SWI ┆ 200 ┆ St. ┆ CHE ┆ 122 ┆ nul ┆ int ┆ 2   ┆ 202 ┆ NHL │
│ dy  ┆ emi ┆     ┆     ┆     ┆     ┆ OS  ┆ SS- ┆ 7-0 ┆ Gal ┆     ┆     ┆ l   ┆ ern ┆     ┆ 5-0 ┆ API │
│     ┆ ah  ┆     ┆     ┆     ┆     ┆ JR. ┆ JR. ┆ 2-2 ┆ len ┆     ┆     ┆     ┆ ati ┆     ┆ 2-1 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆     ┆     ┆     ┆ ona ┆     ┆ 9   ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ l-s ┆     ┆ 16: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ kat ┆     ┆ 26: ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ er  ┆     ┆ 53. ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 670 ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 171 ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

In [38]:
endpoints.DRAFT_RANKINGS_URL.format(year=2023, category=1)

'https://api-web.nhle.com/v1/draft/rankings/2023/1'

In [105]:
scrape_html_events("20242025", "2024020858")

AttributeError: Can only use .str accessor with string values!

In [99]:
game = scrapeGamePlayByPlay(2024020858)

game

,eventId,timeInPeriod,timeRemaining,situationCode,homeTeamDefendingSide,typeCode,event,sortOrder,periodNumber,periodType,periodDescriptor.maxRegulationPeriods,teamId,details.losingPlayerId,details.winningPlayerId,xCoord,yCoord,zoneCode,details.hittingPlayerId,details.hitteePlayerId,reason,shotType,details.shootingPlayerId,goalieInNetId,awaySOG,homeSOG,details.blockingPlayerId,details.playerId,typeCode,descKey,duration,details.committedByPlayerId,details.drawnByPlayerId,pptReplayUrl,details.scoringPlayerId,scoringPlayerTotal,details.assist1PlayerId,assist1PlayerTotal,details.assist2PlayerId,assist2PlayerTotal,awayScore,homeScore,details.highlightClipSharingUrl,details.highlightClipSharingUrlFr,details.highlightClip,details.highlightClipFr,details.discreteClip,details.discreteClipFr,secondaryReason,servedByPlayerId,eventTeam,gameId,period,playerId_1,playerId_2,playerId_3,playerName_1,playerName_2,playerName_3,homeTeam,awayTeam,homeTeamId,awayTeamId,eventTeamType,xFixed,yFixed,meta_datetime,meta_source
0,102,00:00,20:00,1551,left,520,period-start,10,1,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,2024020858,1,NaN,NaN,NaN,NaN,NaN,NaN,SJS,MTL,28,8,away,NaN,NaN,2025-02-17 21:48:42.441570,NHL API
1,101,00:00,20:00,1551,left,502,faceoff,11,1,REG,3,8.0,8479316.0,8481523.0,0.0,0.0,N,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,MTL,2024020858,1,8481523.0,8479316.0,NaN,Kirby Dach,Luke Kunin,NaN,SJS,MTL,28,8,away,0.0,0.0,2025-02-17 21:48:42.441570,NHL API
2,59,00:09,19:51,1551,left,503,hit,12,1,REG,3,8.0,NaN,NaN,-97.0,-7.0,N,8476981.0,8479983.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,MTL,2024020858,1,8476981.0,8479983.0,NaN,Josh Anderson,Mario Ferraro,NaN,SJS,MTL,28,8,away,-97.0,-7.0,2025-02-17 21:48:42.441570,NHL API
3,53,00:22,19:38,1551,left,507,missed-shot,13,1,REG,3,8.0,NaN,NaN,-54.0,37.0,O,NaN,NaN,wide-right,wrist,8481618.0,8480382.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,MTL,2024020858,1,8481618.0,NaN,NaN,Alex Newhook,NaN,NaN,SJS,MTL,28,8,away,-54.0,37.0,2025-02-17 21:48:42.441570,NHL API
4,54,00:31,19:29,1551,left,506,shot-on-goal,15,1,REG,3,28.0,NaN,NaN,34.0,-7.0,O,NaN,NaN,NaN,wrist,8484911.0,8478470.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,SJS,2024020858,1,8484911.0,NaN,NaN,Collin Graf,NaN,NaN,SJS,MTL,28,8,home,34.0,-7.0,2025-02-17 21:48:42.441570,NHL API
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,1001,19:48,00:12,1560,left,504,giveaway,757,3,REG,3,8.0,NaN,NaN,-8.0,17.0,N,NaN,NaN,NaN,NaN,NaN,NaN,16.0,27.0,NaN,8478133.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,MTL,2024020858,3,8478133.0,NaN,NaN,Jake Evans,NaN,NaN,SJS,MTL,28,8,away,-8.0,17.0,2025-02-17 21:48:42.441570,NHL API
303,998,19:55,00:05,1560,left,507,missed-shot,758,3,REG,3,28.0,NaN,NaN,85.0,21.0,O,NaN,NaN,wide-right,wrist,8475726.0,8478470.0,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,SJS,2024020858,3,8475726.0,NaN,NaN,Tyler Toffoli,NaN,NaN,SJS,MTL,28,8,home,85.0,21.0,2025-02-17 21:48:42.441570,NHL API
304,999,19:58,00:02,1560,left,508,blocked-shot,759,3,REG,3,28.0,NaN,NaN,82.0,-4.0,D,NaN,NaN,blocked,NaN,8484227.0,NaN,16.0,27.0,8476875.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,SJS,2024020858,3,8484227.0,8476875.0,NaN,Will Smith,Mike Matheson,NaN,SJS,MTL,28,8,home,82.0,-4.0,2025-02-17 21:48:42.441570,NHL API
305,512,20:00,00:00,1560,left,521,period-end,760,3,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,2024020858,3,NaN,NaN,NaN,NaN,NaN,NaN,SJS,MTL,28,8,away,NaN,NaN,2025-02-17 21:48:42.441570,NHL API
306,516,20:00,00:00,1560,left,524,game-end,764,3,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,2024020858,3,NaN,NaN,NaN,NaN,NaN,NaN,SJS,MTL,28,8,away,NaN,NaN,2025-02-17 21:48:42.441570,NHL API

In [83]:
game[game['details.highlightClipSharingUrl'].notna()]['pptReplayUrl'].iloc[0]

'https://wsr.nhle.com/sprites/20242025/2024020858/ev172.json'

In [17]:
scrapeGameComplete(2024020858)[0]

,eventId,timeInPeriod,timeRemaining,homeTeamDefendingSide,event,sortOrder,periodNumber,periodType,teamId,xCoord,yCoord,zoneCode,reason,shotType,goalieInNetId,awaySOG,homeSOG,typeCode,descKey,duration,scoringPlayerTotal,assist1PlayerTotal,assist2PlayerTotal,awayScore,homeScore,secondaryReason,zoneStartSideDetail_1,zoneStartSide_1,eventTeam,gameId,period,playerId_1,playerId_2,playerId_3,playerName_1,playerName_2,playerName_3,timeInPeriod_s,timeRemaining_s,elapsedTime,homeTeam,awayTeam,homeTeamId,awayTeamId,eventTeamType,xFixed,yFixed
0,102,00:00,20:00,left,period-start,10,1,REG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,2024020858,1,NaN,NaN,NaN,NaN,NaN,NaN,0,1200,0,SJS,MTL,28,8,away,NaN,NaN
1,101,00:00,20:00,left,faceoff,11,1,REG,8.0,0.0,0.0,N,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,MTL,2024020858,1,8481523.0,8479316.0,NaN,Kirby Dach,Luke Kunin,NaN,0,1200,0,SJS,MTL,28,8,away,0.0,0.0
2,59,00:09,19:51,left,hit,12,1,REG,8.0,-97.0,-7.0,N,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,MTL,2024020858,1,8476981.0,8479983.0,NaN,Josh Anderson,Mario Ferraro,NaN,9,1191,9,SJS,MTL,28,8,away,-97.0,-7.0
3,53,00:22,19:38,left,missed-shot,13,1,REG,8.0,-54.0,37.0,O,wide-right,wrist,8480382.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,MTL,2024020858,1,8481618.0,NaN,NaN,Alex Newhook,NaN,NaN,22,1178,22,SJS,MTL,28,8,away,-54.0,37.0
4,54,00:31,19:29,left,shot-on-goal,15,1,REG,28.0,34.0,-7.0,O,NaN,wrist,8478470.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,SJS,2024020858,1,8484911.0,NaN,NaN,Collin Graf,NaN,NaN,31,1169,31,SJS,MTL,28,8,home,34.0,-7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,1001,19:48,00:12,left,giveaway,757,3,REG,8.0,-8.0,17.0,N,NaN,NaN,NaN,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,MTL,2024020858,3,8478133.0,NaN,NaN,Jake Evans,NaN,NaN,1188,12,3588,SJS,MTL,28,8,away,-8.0,17.0
303,998,19:55,00:05,left,missed-shot,758,3,REG,28.0,85.0,21.0,O,wide-right,wrist,8478470.0,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,SJS,2024020858,3,8475726.0,NaN,NaN,Tyler Toffoli,NaN,NaN,1195,5,3595,SJS,MTL,28,8,home,85.0,21.0
304,999,19:58,00:02,left,blocked-shot,759,3,REG,28.0,82.0,-4.0,D,blocked,NaN,NaN,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,SJS,2024020858,3,8484227.0,8476875.0,NaN,Will Smith,Mike Matheson,NaN,1198,2,3598,SJS,MTL,28,8,home,82.0,-4.0
305,512,20:00,00:00,left,period-end,760,3,REG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,2024020858,3,NaN,NaN,NaN,NaN,NaN,NaN,1200,0,3600,SJS,MTL,28,8,away,NaN,NaN
306,516,20:00,00:00,left,game-end,764,3,REG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,NaN,NaN,NaN,2024020858,3,NaN,NaN,NaN,NaN,NaN,NaN,1200,0,3600,SJS,MTL,28,8,away,NaN,NaN

In [3]:
scrapeSkaterOverview(8473512, '20242025', 'regular')

,Metric,Value,League average by position (F/D),Percentile,player_id,season,session,url,scraped_at
0,Top Skating Speed (mph),22.220,22.120,52.0,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
1,Speed Bursts Over 20 mph,44.000,56.200,Below 50th,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
2,Skating Distance (mi),166.350,92.990,91.0,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
3,Top Shot Speed (mph),86.800,83.560,61.0,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
4,Shots on Goal,104.000,65.200,78.0,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
5,Shooting %,0.106,0.126,Below 50th,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
6,Goals,11.000,8.200,65.0,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148
7,Off. Zone Time (ES),0.423,0.413,73.0,8473512,20242025,regular,https://edge.nhl.com/en/skater/20242025-regula...,2025-02-17 09:42:26.470148

In [3]:
scrapeDraft(2024)

,round,pickInRound,overallPick,teamId,teamAbbrev,teamLogoLight,teamLogoDark,teamPickHistory,positionCode,countryCode,height,weight,amateurLeague,amateurClubName,teamName.default,teamName.fr,teamCommonName.default,teamPlaceNameWithPreposition.default,teamPlaceNameWithPreposition.fr,displayAbbrev.default,firstName.default,lastName.default,teamCommonName.fr,lastName.cs,lastName.fi,lastName.sk,meta_datetime,meta_year,meta_round,meta_source
0,1,1,1,28,SJS,https://assets.nhle.com/logos/nhl/svg/SJS_2008...,https://assets.nhle.com/logos/nhl/svg/SJS_2008...,SJS,C,CAN,72,197,H-EAST,Boston University,San Jose Sharks,Sharks de San Jose,Sharks,San Jose,de San Jose,SJS,Macklin,Celebrini,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
1,1,2,2,16,CHI,https://assets.nhle.com/logos/nhl/svg/CHI_ligh...,https://assets.nhle.com/logos/nhl/svg/CHI_dark...,CHI,D,BLR,74,205,BIG10,Michigan State U.,Chicago Blackhawks,Blackhawks de Chicago,Blackhawks,Chicago,de Chicago,CHI,Artyom,Levshunov,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
2,1,3,3,24,ANA,https://assets.nhle.com/logos/nhl/svg/ANA_2013...,https://assets.nhle.com/logos/nhl/svg/ANA_2013...,ANA,RW,CAN,75,182,OHL,Oshawa,Anaheim Ducks,Ducks d'Anaheim,Ducks,Anaheim,d'Anaheim,ANA,Beckett,Sennecke,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
3,1,4,4,29,CBJ,https://assets.nhle.com/logos/nhl/svg/CBJ_ligh...,https://assets.nhle.com/logos/nhl/svg/CBJ_dark...,CBJ,C,CAN,75,213,WHL,Medicine Hat,Columbus Blue Jackets,Blue Jackets de Columbus,Blue Jackets,Columbus,de Columbus,CBJ,Cayden,Lindstrom,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
4,1,5,5,8,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,MTL,RW,RUS,73,192,RUSSIA-JR.,SKA Saint Petersburg Jr.,Montréal Canadiens,Canadiens de Montréal,Canadiens,Montréal,de Montréal,MTL,Ivan,Demidov,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220,7,28,221,23,VAN,https://assets.nhle.com/logos/nhl/svg/VAN_ligh...,https://assets.nhle.com/logos/nhl/svg/VAN_dark...,VAN,D,CHE,75,196,SWISS-JR.,Fribourg Jr.,Vancouver Canucks,Canucks de Vancouver,Canucks,Vancouver,de Vancouver,VAN,Basile,Sansonnens,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
221,7,29,222,25,DAL,https://assets.nhle.com/logos/nhl/svg/DAL_ligh...,https://assets.nhle.com/logos/nhl/svg/DAL_dark...,DAL,C,SWE,72,176,SWEDEN-JR.,Sodertalje Jr.,Dallas Stars,Stars de Dallas,Stars,Dallas,de Dallas,DAL,William,Samuelsson,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
222,7,30,223,5,PIT,https://assets.nhle.com/logos/nhl/svg/PIT_ligh...,https://assets.nhle.com/logos/nhl/svg/PIT_dark...,NYR-PIT,D,CAN,73,198,OHL,Mississauga,Pittsburgh Penguins,Penguins de Pittsburgh,Penguins,Pittsburgh,de Pittsburgh,PIT,Finn,Harding,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
223,7,31,224,8,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,EDM-MTL,D,SWE,74,181,SWEDEN-JR.,Skelleftea Jr.,Montréal Canadiens,Canadiens de Montréal,Canadiens,Montréal,de Montréal,MTL,Rasmus,Bergqvist,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API
224,7,32,225,10,TOR,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...,https://assets.nhle.com/logos/nhl/svg/TOR_dark...,FLA-TOR,D,CAN,76,194,WHL,Spokane,Toronto Maple Leafs,Maple Leafs de Toronto,Maple Leafs,Toronto,de Toronto,TOR,Nathan,Mayes,NaN,NaN,NaN,NaN,2025-02-14 20:12:17.662083,2024,all,NHL API

In [3]:
scrapeTeamDraftHistory(1).head()

,id,ageInDays,ageInDaysForYear,ageInYears,amateurClubName,amateurLeague,birthDate,birthPlace,countryCode,csPlayerId,draftDate,draftMasterId,draftProspect,draftYear,draftedByTeamId,firstName,height,lastName,notes,overallPickNumber,pickInRound,player,playerId,playerName,position,removedOutright,removedOutrightWhy,roundNumber,shootsCatches,supplementalDraft,teamPickHistory,triCode,weight,franchiseTeam.id,franchiseTeam.franchiseId,franchiseTeam.fullName,franchiseTeam.teamCommonName,franchiseTeam.teamId,franchiseTeam.teamPlaceName,team.id,team.commonName,team.fullName,team.logos,team.placeName,team.triCode,player.id,player.birthCountry,player.birthStateProvince,player.firstName,player.lastName,player.onRoster,player.position,player.yearsPro,draftProspect.id,meta_datetime,meta_source
0,7057,5914.0,70.0,16.0,Georgetown Midgets,None,1947-03-27,"Georgetown, ON CAN",CAN,NaN,1963-06-05,1,NaN,1963,8,Rodney,NaN,Presswood,None,7,1,NaN,NaN,Rodney Presswood,D,N,None,2,None,N,MTL,MTL,NaN,1,1,Montréal Canadiens,Canadiens,8,Montréal,8,Canadiens,Montréal Canadiens,"[{'id': 48, 'background': 'light', 'endSeason'...",Montréal,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 22:57:52.811775,NHL Records API
1,7063,6047.0,203.0,16.0,None,Aurora Jr. C,1946-11-14,"Newmarket, ON CAN",CAN,NaN,1963-06-05,1,NaN,1963,8,Roy,69.0,Pugh,None,13,1,NaN,NaN,Roy Pugh,C,N,None,3,L,N,MTL,MTL,175.0,1,1,Montréal Canadiens,Canadiens,8,Montréal,8,Canadiens,Montréal Canadiens,"[{'id': 48, 'background': 'light', 'endSeason'...",Montréal,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 22:57:52.811775,NHL Records API
2,7068,5804.0,325.0,15.0,Port Colborne Midgets,None,1947-07-15,"Wainfleet, ON CAN",CAN,NaN,1963-06-05,1,NaN,1963,8,Glen,70.0,Shirton,None,18,1,NaN,NaN,Glen Shirton,D,N,None,4,L,N,MTL,MTL,170.0,1,1,Montréal Canadiens,Canadiens,8,Montréal,8,Canadiens,Montréal Canadiens,"[{'id': 48, 'background': 'light', 'endSeason'...",Montréal,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 22:57:52.811775,NHL Records API
3,7077,5926.0,82.0,16.0,Rosemount Midgets,None,1948-03-21,"St. Pierre, QC CAN",CAN,NaN,1964-06-11,2,NaN,1964,8,Claude,NaN,Chagnon,None,6,6,NaN,NaN,Claude Chagnon,D,N,None,1,None,N,MTL,MTL,NaN,1,1,Montréal Canadiens,Canadiens,8,Montréal,8,Canadiens,Montréal Canadiens,"[{'id': 48, 'background': 'light', 'endSeason'...",Montréal,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 22:57:52.811775,NHL Records API
4,7083,6088.0,244.0,16.0,None,Stamford Jr. B,1947-10-11,"Schumacher, ON CAN",CAN,NaN,1964-06-11,2,NaN,1964,8,Guy,73.0,Allen,None,12,6,NaN,NaN,Guy Allen,D,N,None,2,R,N,MTL,MTL,200.0,1,1,Montréal Canadiens,Canadiens,8,Montréal,8,Canadiens,Montréal Canadiens,"[{'id': 48, 'background': 'light', 'endSeason'...",Montréal,MTL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 22:57:52.811775,NHL Records API

In [17]:
scrapeActiveTeams().head()

,teamId,abbrev,name,commonName,placeNameWithPreposition,logo,darkLogo,meta_datetime,meta_source
0,1,NJD,New Jersey Devils,Devils,New Jersey,https://assets.nhle.com/logos/nhl/svg/NJD_ligh...,https://assets.nhle.com/logos/nhl/svg/NJD_dark...,2025-02-13 22:32:37.870054,NHL API
1,2,NYI,New York Islanders,Islanders,New York,https://assets.nhle.com/logos/nhl/svg/NYI_ligh...,https://assets.nhle.com/logos/nhl/svg/NYI_dark...,2025-02-13 22:32:37.870054,NHL API
2,3,NYR,New York Rangers,Rangers,New York,https://assets.nhle.com/logos/nhl/svg/NYR_ligh...,https://assets.nhle.com/logos/nhl/svg/NYR_dark...,2025-02-13 22:32:37.870054,NHL API
3,4,PHI,Philadelphia Flyers,Flyers,Philadelphia,https://assets.nhle.com/logos/nhl/svg/PHI_ligh...,https://assets.nhle.com/logos/nhl/svg/PHI_dark...,2025-02-13 22:32:37.870054,NHL API
4,5,PIT,Pittsburgh Penguins,Penguins,Pittsburgh,https://assets.nhle.com/logos/nhl/svg/PIT_ligh...,https://assets.nhle.com/logos/nhl/svg/PIT_dark...,2025-02-13 22:32:37.870054,NHL API

In [15]:
scrapeTeamAffiliates().head()

,franchiseId,teamAffiliateId,teamId,teamAffiliate.fullName,teamAffiliate.league.abbreviation,teamAffiliate.officialSiteUrl,teamAffiliate,meta_datetime,meta_source
0,32,7297,24,San Diego Gulls,AHL,http://www.sandiegogulls.com/,NaN,2025-02-13 22:28:47.347120,NHL Records API
1,32,6706,24,Tulsa Oilers,ECHL,https://tulsaoilers.com/,NaN,2025-02-13 22:28:47.347120,NHL Records API
2,6,4982,6,Providence Bruins,AHL,http://www.providencebruins.com/,NaN,2025-02-13 22:28:47.347120,NHL Records API
3,19,6674,7,Rochester Americans,AHL,http://www.amerks.com/home,NaN,2025-02-13 22:28:47.347120,NHL Records API
4,19,7638,7,Jacksonville Icemen,ECHL,https://www.jacksonvilleicemen.com/,NaN,2025-02-13 22:28:47.347120,NHL Records API

In [13]:
scrapeTeamDetails().head()

,id,firstSeasonId,fullName,lastSeasonId,mostRecentTeamId,teamAbbrev,teamCommonName,teamPlaceName,teams,meta_datetime,meta_source
0,1,19171918,Montréal Canadiens,NaN,8,MTL,Canadiens,Montréal,"[{'id': 8, 'active': 'Y', 'commonName': 'Canad...",2025-02-13 22:27:58.922569,NHL Records API
1,2,19171918,Montreal Wanderers,19171918.0,41,MWN,Wanderers,Montreal,"[{'id': 41, 'active': 'N', 'commonName': 'Wand...",2025-02-13 22:27:58.922569,NHL Records API
2,3,19171918,St. Louis Eagles,19341935.0,45,SLE,Eagles,St. Louis,"[{'id': 36, 'active': 'N', 'commonName': 'Sena...",2025-02-13 22:27:58.922569,NHL Records API
3,4,19191920,Hamilton Tigers,19241925.0,37,HAM,Tigers,Hamilton,"[{'id': 37, 'active': 'N', 'commonName': 'Tige...",2025-02-13 22:27:58.922569,NHL Records API
4,5,19171918,Toronto Maple Leafs,NaN,10,TOR,Maple Leafs,Toronto,"[{'id': 10, 'active': 'Y', 'commonName': 'Mapl...",2025-02-13 22:27:58.922569,NHL Records API

In [11]:
scrapeTeamProspects('MTL').head()

,playerId,headshot,sweaterNumber,positionCode,shootsCatches,heightInInches,weightInPounds,heightInCentimeters,weightInKilograms,birthDate,birthCountry,firstName.default,lastName.default,birthCity.default,birthStateProvince.default,birthCity.cs,birthCity.fi,birthCity.fr,birthCity.sk,birthStateProvince.fr,birthStateProvince.sk,birthStateProvince.sv,birthCity.sv,fullName,position,positionD,team,meta_datetime,meta_source
0,8483424,https://assets.nhle.com/mugs/nhl/20222023/MTL/...,62.0,C,R,72,190,183,86,2004-02-03,CAN,Owen,Beck,Port Hope,Ontario,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Owen Beck,F,F,MTL,2025-02-13 22:27:09.206301,NHL API
1,8483549,https://assets.nhle.com/mugs/nhl/20222023/MTL/...,73.0,C,L,73,223,185,101,1997-06-19,CAN,Lucas,Condotta,Georgetown,Ontario,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lucas Condotta,F,F,MTL,2025-02-13 22:27:09.206301,NHL API
2,8483728,https://assets.nhle.com/mugs/nhl/latest/848372...,76.0,C,L,71,183,180,83,2002-07-07,CAN,Jared,Davidson,Edmonton,Alberta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jared Davidson,F,F,MTL,2025-02-13 22:27:09.206301,NHL API
3,8484448,https://assets.nhle.com/mugs/nhl/latest/848444...,NaN,C,L,71,179,180,81,2004-11-05,SWE,Filip,Eriksson,Ljungby,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Filip Eriksson,F,F,MTL,2025-02-13 22:27:09.206301,NHL API
4,8482081,https://assets.nhle.com/mugs/nhl/20222023/MTL/...,57.0,C,L,69,175,175,79,2001-11-02,USA,Sean,Farrell,Milford,Massachusetts,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sean Farrell,F,F,MTL,2025-02-13 22:27:09.206301,NHL API

In [9]:
scrapeTeamStats('MTL', '20242025', 2, True)

,playerId,headshot,gamesPlayed,gamesStarted,wins,losses,ties,overtimeLosses,goalsAgainstAverage,savePercentage,shotsAgainst,saves,goalsAgainst,shutouts,goals,assists,points,penaltyMinutes,timeOnIce,firstName.default,lastName.default,fullName,team,season,session,sessionCode,meta_datetime,meta_source
0,8478470,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,42,40,18,21,0,3,2.995331,0.896705,1123,1007,116,3,0,0,0,0,139417,Sam,Montembeault,Sam Montembeault,MTL,20242025,regular,2,2025-02-13 22:18:21.415106,NHL API
1,8480051,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,11,7,2,3,0,1,4.697346,0.836000,250,209,41,0,0,0,0,2,31422,Cayden,Primeau,Cayden Primeau,MTL,20242025,regular,2,2025-02-13 22:18:21.415106,NHL API
2,8482487,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,9,9,5,2,0,1,2.705440,0.907631,249,226,23,1,0,0,0,0,30605,Jakub,Dobes,Jakub Dobes,MTL,20242025,regular,2,2025-02-13 22:18:21.415106,NHL API

In [5]:
scrapeTeamSchedule('MTL', '20242025')

,id,season,gameType,gameDate,neutralSite,startTimeUTC,easternUTCOffset,venueUTCOffset,venueTimezone,gameState,gameScheduleState,tvBroadcasts,threeMinRecapFr,condensedGameFr,gameCenterLink,venue.default,awayTeam.id,awayTeam.commonName.default,awayTeam.placeName.default,awayTeam.placeName.fr,awayTeam.placeNameWithPreposition.default,awayTeam.placeNameWithPreposition.fr,awayTeam.abbrev,awayTeam.logo,awayTeam.darkLogo,awayTeam.awaySplitSquad,awayTeam.score,homeTeam.id,homeTeam.commonName.default,homeTeam.placeName.default,homeTeam.placeNameWithPreposition.default,homeTeam.placeNameWithPreposition.fr,homeTeam.abbrev,homeTeam.logo,homeTeam.darkLogo,homeTeam.homeSplitSquad,homeTeam.score,periodDescriptor.periodType,periodDescriptor.maxRegulationPeriods,gameOutcome.lastPeriodType,winningGoalie.playerId,winningGoalie.firstInitial.default,winningGoalie.lastName.default,winningGoalScorer.playerId,winningGoalScorer.firstInitial.default,winningGoalScorer.lastName.default,threeMinRecap,awayTeam.commonName.fr,venue.fr,homeTeam.commonName.fr,homeTeam.airlineLink,homeTeam.airlineDesc,winningGoalie.lastName.cs,winningGoalie.lastName.fi,winningGoalie.lastName.sk,homeTeam.placeName.fr,condensedGame,winningGoalie.lastName.sv,homeTeam.hotelLink,homeTeam.hotelDesc,awayTeam.airlineLink,awayTeam.airlineDesc,awayTeam.hotelLink,awayTeam.hotelDesc,winningGoalScorer.lastName.cs,winningGoalScorer.lastName.fi,winningGoalScorer.lastName.sk,winningGoalScorer.lastName.sv,venue.es,ticketsLink,ticketsLinkFr,awayTeam.radioLink,homeTeam.radioLink,awayTeam.promoLink,awayTeam.promoDesc,homeTeam.promoLink,homeTeam.promoDesc,teamAbbrev,meta_datetime,meta_source
0,2024010015,20242025,1,2024-09-23,False,2024-09-23 23:00:00+00:00,-04:00,-04:00,America/Montreal,FINAL,OK,"[{'id': 33, 'market': 'H', 'countryCode': 'CA'...",/fr/video/recap-flyers-at-canadiens-9-23-24-63...,/fr/video/condensed-game-flyers-at-canadiens-9...,/gamecenter/phi-vs-mtl/2024/09/23/2024010015,Centre Bell,4,Flyers,Philadelphia,Philadelphie,Philadelphia,de Philadelphie,PHI,https://assets.nhle.com/logos/nhl/svg/PHI_ligh...,https://assets.nhle.com/logos/nhl/svg/PHI_dark...,False,0.0,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,5.0,REG,3,REG,8480051.0,C.,Primeau,8482134.0,L.,Tuch,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
1,2024010022,20242025,1,2024-09-24,False,2024-09-24 23:00:00+00:00,-04:00,-04:00,America/Montreal,FINAL,OK,"[{'id': 33, 'market': 'H', 'countryCode': 'CA'...",/fr/video/recap-devils-at-canadiens-9-24-24-63...,NaN,/gamecenter/njd-vs-mtl/2024/09/24/2024010022,Centre Bell,1,Devils,New Jersey,NaN,New Jersey,du New Jersey,NJD,https://assets.nhle.com/logos/nhl/svg/NJD_ligh...,https://assets.nhle.com/logos/nhl/svg/NJD_dark...,False,0.0,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,3.0,REG,3,REG,8478470.0,S.,Montembeault,8479543.0,M.,Pezzetta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
2,2024010038,20242025,1,2024-09-26,False,2024-09-26 23:00:00+00:00,-04:00,-04:00,America/Toronto,FINAL,OK,"[{'id': 282, 'market': 'N', 'countryCode': 'CA...",/fr/video/recap-canadiens-at-leafs-9-26-24-636...,/fr/video/condensed-game-canadiens-at-leafs-9-...,/gamecenter/mtl-vs-tor/2024/09/26/2024010038,Scotiabank Arena,8,Canadiens,Montréal,NaN,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,1.0,10,Maple Leafs,Toronto,Toronto,de Toronto,TOR,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...,https://assets.nhle.com/logos/nhl/svg/TOR_dark...,False,2.0,REG,3,REG,8476932.0,A.,Stolarz,8481582.0,N.,Robertson,/video/recap-canadiens-at-leafs-9-26-24-636252...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
3,2024010055,20242025,1,2024-09-28,False,2024-09-28 23:00:00+00:00,-04:00,-04:00,America/Montreal,FINAL,OK,"[{'id': 131, 'market': 'H', 'countryCode': 'CA...",/fr/video/recap-leafs-at-canadiens-9-28-24-636...,NaN,/gamecenter/tor-vs-mtl/2024/09/28/2024010055,Centre Bell,10,Maple Leafs,Toronto,NaN,Toronto,de Toronto,TOR,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...,https://assets.nhle.com/logos/nhl/svg/TOR_dark...,False,2.0,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,1.0,REG,3,REG,8483710.0,D.,Hildeby,8481582.0,N.,Robertson,/video/recap-leafs-at-canadiens-9-28-24-636262...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
4,2024010073,20242025,1,2024-10-01,False,2024-10-01 23:00:00+00:00,-04:00,-04:00,America/Montreal,FINAL,OK,"[{'id': 131, 'market': 'H', 'countryCode': 'CA...",/fr/video/recap-senators-at-canadiens-10-1-24-...,NaN,/gamecenter/ott-vs-mtl/2024/10/01/2024010073,Centre Bell,9,Senators,Ottawa,NaN,Ottawa,d'Ottawa,OTT,https://assets.nhle.com/logos/nhl/svg/OTT_ligh...,https://assets.nhle.com/logos/nhl/svg/OTT_dark...,False,4.0,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,3.0,REG,3,REG,8476999.0,L.,Ullmark,8484759.0,C.,Yakemchuk,/video/recap-senators-at-canadiens-10-1-24-636...,Sénateurs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,2024021236,20242025,2,2025-04-08,False,2025-04-08 23:00:00+00:00,-04:00,-04:00,America/Montreal,FUT,OK,"[{'id': 131, 'market': 'H', 'countryCode': 'CA...",NaN,NaN,/gamecenter/det-vs-mtl/2025/04/08/2024021236,Centre Bell,17,Red Wings,Detroit,NaN,Detroit,de Detroit,DET,https://assets.nhle.com/logos/nhl/svg/DET_ligh...,https://assets.nhle.com/logos/nhl/svg/DET_dark...,False,NaN,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,NaN,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ticketmaster.ca/event/310060F97F9B...,https://www.ticketmaster.ca/event/310060F97F9B...,https://d2igy0yla8zi0u.cloudfront.net/DET/2024...,https://d2igy0yla8zi0u.cloudfront.net/MTL/2024...,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
84,2024021260,20242025,2,2025-04-11,False,2025-04-11 23:00:00+00:00,-04:00,-04:00,US/Eastern,FUT,OK,"[{'id': 287, 'market': 'N', 'countryCode': 'CA...",NaN,NaN,/gamecenter/mtl-vs-ott/2025/04/11/2024021260,Canadian Tire Centre,8,Canadiens,Montréal,NaN,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,NaN,9,Senators,Ottawa,Ottawa,d'Ottawa,OTT,https://assets.nhle.com/logos/nhl/svg/OTT_ligh...,https://assets.nhle.com/logos/nhl/svg/OTT_dark...,False,NaN,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Centre Canadian Tire,Sénateurs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ticketmaster.ca/event/31006107F9ED...,https://www.nhl.com/fr/senators/tickets/,https://d2igy0yla8zi0u.cloudfront.net/MTL/2024...,https://d2igy0yla8zi0u.cloudfront.net/OTT/2024...,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
85,2024021269,20242025,2,2025-04-12,False,2025-04-12 23:00:00+00:00,-04:00,-04:00,America/Toronto,FUT,OK,"[{'id': 4, 'market': 'N', 'countryCode': 'CA',...",NaN,NaN,/gamecenter/mtl-vs-tor/2025/04/12/2024021269,Scotiabank Arena,8,Canadiens,Montréal,NaN,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,NaN,10,Maple Leafs,Toronto,Toronto,de Toronto,TOR,https://assets.nhle.com/logos/nhl/svg/TOR_ligh...,https://assets.nhle.com/logos/nhl/svg/TOR_dark...,False,NaN,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.marriott.com/default.mi?scid=cfdfa...,Book Now,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.nhl.com/mapleleafs/tickets/,https://www.nhl.com/mapleleafs/tickets/,https://d2igy0yla8zi0u.cloudfront.net/MTL/2024...,https://d2igy0yla8zi0u.cloudfront.net/TOR/2024...,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
86,2024021285,20242025,2,2025-04-14,False,2025-04-14 23:00:00+00:00,-04:00,-04:00,America/Montreal,FUT,OK,"[{'id': 548, 'market': 'N', 'countryCode': 'CA...",NaN,NaN,/gamecenter/chi-vs-mtl/2025/04/14/2024021285,Centre Bell,16,Blackhawks,Chicago,NaN,Chicago,de Chicago,CHI,https://assets.nhle.com/logos/nhl/svg/CHI_ligh...,https://assets.nhle.com/logos/nhl/svg/CHI_dark...,False,NaN,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,NaN,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.ticketmaster.ca/event/310060F97F9E...,https://www.ticketmaster.ca/event/310060F97F9E...,https://d2igy0yla8zi0u.cloudfront.net/CHI/2024...,https://d2igy0yla8zi0u.cloudfront.net/MTL/2024...,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API
87,2024021301,20242025,2,2025-04-16,False,2025-04-16 23:00:00+00:00,-04:00,-04:00,America/Montreal,FUT,OK,"[{'id': 287, 'market': 'N', 'countryCode': 'CA...",NaN,NaN,/gamecenter/car-vs-mtl/2025/04/16/2024021301,Centre Bell,12,Hurricanes,Carolina,Caroline,Carolina,de la Caroline,CAR,https://assets.nhle.com/logos/nhl/svg/CAR_ligh...,https://assets.nhle.com/logos/nhl/svg/CAR_dark...,False,NaN,8,Canadiens,Montréal,Montréal,de Montréal,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,False,NaN,REG,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://hurricanes.bookseats.com/build-package...,Travel Packages,https://hurricanes.bookseats.com/build-package...,Travel Packages,NaN,NaN,NaN,NaN,NaN,https://www.ticketmaster.ca/event/310060F97FA2...,https://www.ticketmaster.ca/event/310060F97FA2...,https://d2igy0yla8zi0u.cloudfront.net/CAR/2024...,https://d2igy0yla8zi0u.cloudfront.net/MTL/2024...,NaN,NaN,NaN,NaN,MTL,2025-02-13 22:14:38.540136,NHL API

In [4]:
scrapeTeamRoster('MTL', 20242025).head()

,playerId,headshot,sweaterNumber,positionCode,shootsCatches,heightInInches,weightInPounds,heightInCentimeters,weightInKilograms,birthDate,birthCountry,firstName.default,lastName.default,birthCity.default,birthStateProvince.default,birthCity.sv,lastName.cs,lastName.sk,birthCity.cs,birthCity.fi,birthCity.sk,birthCity.fr,fullName,position,positionD,team,season,meta_datetime,meta_source
0,8476981,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,17,R,R,75,226,191,103,1994-05-07,CAN,Josh,Anderson,Burlington,ON,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Josh Anderson,F,F,MTL,20242025,2025-02-13 22:13:52.617920,NHL API
1,8476469,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,40,R,R,75,216,191,98,1993-05-31,FIN,Joel,Armia,Pori,NaN,Björneborg,NaN,NaN,NaN,NaN,NaN,NaN,Joel Armia,F,F,MTL,20242025,2025-02-13 22:13:52.617920,NHL API
2,8481540,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,13,R,R,68,175,173,79,2001-01-02,USA,Cole,Caufield,Mosinee,WI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cole Caufield,F,F,MTL,20242025,2025-02-13 22:13:52.617920,NHL API
3,8481523,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,77,C,R,76,221,193,100,2001-01-21,CAN,Kirby,Dach,Fort Saskatchewan,AB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Kirby Dach,F,F,MTL,20242025,2025-02-13 22:13:52.617920,NHL API
4,8477989,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,28,C,L,73,190,185,86,1996-02-02,USA,Christian,Dvorak,Palos,IL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Christian Dvorak,F,F,MTL,20242025,2025-02-13 22:13:52.617920,NHL API

In [13]:
scrapeTeams().head()

,teamId,fullName,lastSeason,teamCommonName,teamPlaceName,firstSeason.id,lastSeason.id,meta_datetime,meta_source
0,32,Anaheim Ducks,NaN,Ducks,Anaheim,19931994,NaN,2025-02-13 22:10:31.502837,NHL Stats API
1,28,Arizona Coyotes,NaN,Coyotes,Arizona,19791980,20232024.0,2025-02-13 22:10:31.502837,NHL Stats API
2,6,Boston Bruins,NaN,Bruins,Boston,19241925,NaN,2025-02-13 22:10:31.502837,NHL Stats API
3,8,Brooklyn Americans,NaN,Americans,Brooklyn,19251926,19411942.0,2025-02-13 22:10:31.502837,NHL Stats API
4,19,Buffalo Sabres,NaN,Sabres,Buffalo,19701971,NaN,2025-02-13 22:10:31.502837,NHL Stats API

In [6]:
scrapePlayerGameLog(8481540, 20232024, 2).head()

,gameId,teamAbbrev,homeRoadFlag,gameDate,goals,assists,points,plusMinus,powerPlayGoals,powerPlayPoints,gameWinningGoals,otGoals,shots,shifts,shorthandedGoals,shorthandedPoints,opponentAbbrev,pim,toi,commonName.default,opponentCommonName.default,opponentCommonName.fr,playerId,playerName,position,meta_datetime,meta_source
0,2023021298,MTL,H,2024-04-16,1,0,1,0,0,0,0,0,4,25,0,0,DET,0,22:32,Canadiens,Red Wings,NaN,8481540,Cole Caufield,R,2025-02-13 22:04:17.045725,NHL API
1,2023021287,MTL,R,2024-04-15,0,0,0,0,0,0,0,0,4,22,0,0,DET,0,21:05,Canadiens,Red Wings,NaN,8481540,Cole Caufield,R,2025-02-13 22:04:17.045725,NHL API
2,2023021276,MTL,R,2024-04-13,2,0,2,1,1,1,0,0,6,21,0,0,OTT,0,17:30,Canadiens,Senators,Sénateurs,8481540,Cole Caufield,R,2025-02-13 22:04:17.045725,NHL API
3,2023021261,MTL,R,2024-04-11,1,1,2,1,0,0,0,0,4,22,0,0,NYI,0,16:35,Canadiens,Islanders,NaN,8481540,Cole Caufield,R,2025-02-13 22:04:17.045725,NHL API
4,2023021242,MTL,H,2024-04-09,0,1,1,0,0,0,0,0,1,17,0,0,PHI,0,16:48,Canadiens,Flyers,NaN,8481540,Cole Caufield,R,2025-02-13 22:04:17.045725,NHL API

In [3]:
scrapePlayerStats(8481540, stats_type='seasonTotals').head()

,assists,gameTypeId,gamesPlayed,goals,leagueAbbrev,pim,points,season,sequence,teamName.default,plusMinus,avgToi,faceoffWinningPctg,gameWinningGoals,otGoals,powerPlayGoals,powerPlayPoints,shootingPctg,shorthandedGoals,shorthandedPoints,shots,teamCommonName.default,teamName.fr,teamPlaceNameWithPreposition.default,teamPlaceNameWithPreposition.fr,firstName,lastName,fullName,positionCode,position,currentTeamId,currentTeamAbbrev,playerId,meta_datetime,meta_source
0,9,2,6,9,Brick Invitational,4.0,18,20102011,128836,Chicago Jr. Blackhawks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cole,Caufield,Cole Caufield,R,F,8,MTL,8481540,2025-02-13 22:00:40.363016,NHL API
1,9,3,6,9,Brick Invitational,4.0,18,20102011,129687,Chicago Jr. Blackhawks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cole,Caufield,Cole Caufield,R,F,8,MTL,8481540,2025-02-13 22:00:40.363016,NHL API
2,9,2,19,18,HPMBHL,4.0,27,20142015,141486,Team Illinois Bantam Minor AAA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cole,Caufield,Cole Caufield,R,F,8,MTL,8481540,2025-02-13 22:00:40.363016,NHL API
3,33,2,23,25,USHS-WI,6.0,58,20152016,91191,Stevens Point Area High,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cole,Caufield,Cole Caufield,R,F,8,MTL,8481540,2025-02-13 22:00:40.363016,NHL API
4,31,2,37,23,14U AAA,NaN,54,20152016,192638,Team Wisconsin 14U AAA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cole,Caufield,Cole Caufield,R,F,8,MTL,8481540,2025-02-13 22:00:40.363016,NHL API

In [91]:
scrapeGameShiftsLegacy(2024020858)

,Shift Number,Period,Duration,Event,is_home,Player Name,Player Number,firstName,lastName,Start Time (Elapsed),Start Time (Remaining),End Time (Elapsed),End Time (Remaining),Start Time (Elapsed) (Seconds),Start Time (Remaining) (Seconds),End Time (Elapsed) (Seconds),End Time (Remaining) (Seconds),Duration (Seconds),startTimeInSeconds,endTimeInSeconds,sweaterNumber,gameId,source,season,meta_datetime,meta_source
38,1.0,1,00:33,,1,"THRUN, HENRY",3,HENRY,THRUN,0:00,20:00,0:33,19:27,0,1200,33,1167,33,0,33,3,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
411,1.0,1,00:33,,0,"SUZUKI, NICK",14,NICK,SUZUKI,0:00,20:00,0:33,19:27,0,1200,33,1167,33,0,33,14,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
427,1.0,1,00:33,,0,"NEWHOOK, ALEX",15,ALEX,NEWHOOK,0:00,20:00,0:33,19:27,0,1200,33,1167,33,0,33,15,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
104,1.0,1,00:33,,1,"POTURALSKI, ANDREW",22,ANDREW,POTURALSKI,0:00,20:00,0:33,19:27,0,1200,33,1167,33,0,33,22,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
123,1.0,1,00:30,,1,"GOODROW, BARCLAY",23,BARCLAY,GOODROW,0:00,20:00,0:30,19:30,0,1200,30,1170,30,0,30,23,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
410,18.0,3,01:13,,0,"SUZUKI, NICK",14,NICK,SUZUKI,18:47,1:13,20:00,0:00,1127,73,1200,0,73,3527,3600,14,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
210,23.0,3,00:36,,1,"GRAF, COLLIN",51,COLLIN,GRAF,18:48,1:12,19:24,0:36,1128,72,1164,36,36,3528,3564,51,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
87,18.0,3,01:10,,1,"ZETTERLUND, FABIAN",20,FABIAN,ZETTERLUND,18:50,1:10,20:00,0:00,1130,70,1200,0,70,3530,3600,20,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
263,22.0,3,00:36,,1,"EKLUND, WILLIAM",72,WILLIAM,EKLUND,19:24,0:36,20:00,0:00,1164,36,1200,0,36,3564,3600,72,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports
283,20.0,3,00:36,,1,"TOFFOLI, TYLER",73,TYLER,TOFFOLI,19:24,0:36,20:00,0:00,1164,36,1200,0,36,3564,3600,73,2024020858,HTML,20242025,2025-02-17 21:20:22.482425,NHL HTML Reports

In [7]:
# Test Draft Functions
draft_df = scrapeDraft(year=2023, round="all")
draft_df.head()

,round,pickInRound,overallPick,teamId,teamAbbrev,teamLogoLight,teamLogoDark,teamPickHistory,positionCode,countryCode,height,weight,amateurLeague,amateurClubName,teamName.default,teamName.fr,teamCommonName.default,teamPlaceNameWithPreposition.default,teamPlaceNameWithPreposition.fr,displayAbbrev.default,firstName.default,lastName.default,firstName.cs,firstName.sk,lastName.cs,lastName.fi,lastName.sk,teamCommonName.fr,meta_datetime,meta_year,meta_round,meta_source
0,1,1,1,16,CHI,https://assets.nhle.com/logos/nhl/svg/CHI_ligh...,https://assets.nhle.com/logos/nhl/svg/CHI_dark...,CHI,C,CAN,70,185,WHL,Regina,Chicago Blackhawks,Blackhawks de Chicago,Blackhawks,Chicago,de Chicago,CHI,Connor,Bedard,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 17:46:25.524795,2023,all,NHL API
1,1,2,2,24,ANA,https://assets.nhle.com/logos/nhl/svg/ANA_2013...,https://assets.nhle.com/logos/nhl/svg/ANA_2013...,ANA,C,SWE,74,194,SWEDEN,Orebro,Anaheim Ducks,Ducks d'Anaheim,Ducks,Anaheim,d'Anaheim,ANA,Leo,Carlsson,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 17:46:25.524795,2023,all,NHL API
2,1,3,3,29,CBJ,https://assets.nhle.com/logos/nhl/svg/CBJ_ligh...,https://assets.nhle.com/logos/nhl/svg/CBJ_dark...,CBJ,C,CAN,74,195,BIG10,Michigan,Columbus Blue Jackets,Blue Jackets de Columbus,Blue Jackets,Columbus,de Columbus,CBJ,Adam,Fantilli,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 17:46:25.524795,2023,all,NHL API
3,1,4,4,28,SJS,https://assets.nhle.com/logos/nhl/svg/SJS_2008...,https://assets.nhle.com/logos/nhl/svg/SJS_2008...,SJS,C,USA,72,180,NTDP,USA U-18,San Jose Sharks,Sharks de San Jose,Sharks,San Jose,de San Jose,SJS,Will,Smith,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 17:46:25.524795,2023,all,NHL API
4,1,5,5,8,MTL,https://assets.nhle.com/logos/nhl/svg/MTL_ligh...,https://assets.nhle.com/logos/nhl/svg/MTL_dark...,MTL,D,AUT,74,194,SWISS,Kloten,Montréal Canadiens,Canadiens de Montréal,Canadiens,Montréal,de Montréal,MTL,David,Reinbacher,NaN,NaN,NaN,NaN,NaN,NaN,2025-02-13 17:46:25.524795,2023,all,NHL API

In [18]:
scrapeRankings()

,lastName,firstName,positionCode,shootsCatches,heightInInches,weightInPounds,lastAmateurClub,lastAmateurLeague,birthDate,birthCity,birthStateProvince,birthCountry,midtermRank,meta_datetime,meta_year,meta_category,meta_category_name
0,Schaefer,Matthew,D,L,74,183,ERIE,OHL,2007-09-05,Hamilton,ON,CAN,1,2025-02-13 22:33:46.497560,2025,1,north-american-skater
1,Hagens,James,C,L,70,177,BOSTON COLLEGE,H-EAST,2006-11-03,Hauppauge,NY,USA,2,2025-02-13 22:33:46.497560,2025,1,north-american-skater
2,Misa,Michael,C,L,73,184,SAGINAW,OHL,2007-02-16,Oakville,ON,CAN,3,2025-02-13 22:33:46.497560,2025,1,north-american-skater
3,Martone,Porter,RW,R,75,208,BRAMPTON,OHL,2006-10-26,Peterborough,ON,CAN,4,2025-02-13 22:33:46.497560,2025,1,north-american-skater
4,McQueen,Roger,C,R,77,197,BRANDON,WHL,2006-10-02,Saskatoon,SK,CAN,5,2025-02-13 22:33:46.497560,2025,1,north-american-skater
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221,Wyttenbach,Ethan,LW,R,70,180,SIOUX FALLS,USHL,2007-02-10,Roslyn,NY,USA,222,2025-02-13 22:33:46.497560,2025,1,north-american-skater
222,Corbet,Nate,D,L,73,171,KELOWNA,WHL,2006-03-15,Mannheim,NaN,DEU,223,2025-02-13 22:33:46.497560,2025,1,north-american-skater
223,Kachkowski,Jack,D,R,72,176,SASKATOON,WHL,2007-01-14,St. Albert,AB,CAN,224,2025-02-13 22:33:46.497560,2025,1,north-american-skater
224,Dragusica,Luke,D,L,73,178,BRAMPTON,OHL,2007-02-16,Hamilton,ON,CAN,925,2025-02-13 22:33:46.497560,2025,1,north-american-skater
225,Tuminaro,Cole,D,R,76,223,SIOUX CITY,USHL,2007-01-24,Rockford,IL,USA,926,2025-02-13 22:33:46.497560,2025,1,north-american-skater

In [2]:
# Test Game Functions
game_id = 2024020858  # First game of 2023-24 season
roster_df = scrapeGameRosters(game_id)

roster_df.head()

,teamId,playerId,sweaterNumber,positionCode,position,headshot,firstName.default,lastName.default,lastName.cs,lastName.sk,lastName.fi,lastName.sv,firstName.fi,teamAbbrev,is_home,gameId,gameDatetime,gameType,season,meta_datetime,meta_source
19,8,8480018,14,C,F,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,Nick,Suzuki,NaN,NaN,NaN,NaN,NaN,MTL,0,2024020858,2025-02-04,2,20242025,2025-02-13 17:54:13.646929,NHL API
27,8,8481618,15,C,F,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,Alex,Newhook,NaN,NaN,NaN,NaN,NaN,MTL,0,2024020858,2025-02-04,2,20242025,2025-02-13 17:54:13.646929,NHL API
8,8,8477989,28,C,F,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,Christian,Dvorak,NaN,NaN,NaN,NaN,NaN,MTL,0,2024020858,2025-02-04,2,20242025,2025-02-13 17:54:13.646929,NHL API
34,8,8483424,62,C,F,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,Owen,Beck,NaN,NaN,NaN,NaN,NaN,MTL,0,2024020858,2025-02-04,2,20242025,2025-02-13 17:54:13.646929,NHL API
10,8,8478133,71,C,F,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,Jake,Evans,NaN,NaN,NaN,NaN,NaN,MTL,0,2024020858,2025-02-04,2,20242025,2025-02-13 17:54:13.646929,NHL API

In [2]:
shifts_df = scrapeGameShifts(2024020858)

shifts_df

,id,playerId,firstName,lastName,startTime,endTime,duration,period,shiftNumber,teamAbbrev,teamId,teamName,gameId,hexValue,eventDescription,eventDetails,eventNumber,typeCode,detailCode,sweaterNumber,positionCode,position,headshot,is_home,fullName,shiftDuration,startTimeInSeconds,endTimeInSeconds,gameTimeStart,gameTimeEnd,gameDatetime,gameType,season,meta_datetime,meta_source
0,15036138,8475233,David,Savard,01:18,02:02,00:44,1,1,MTL,8,Montréal Canadiens,2024020858,#A6192E,None,None,66,517,0,58,D,D,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,0,David Savard,44,78,122,78,122,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
1,15036139,8475233,David,Savard,03:59,05:11,01:12,1,2,MTL,8,Montréal Canadiens,2024020858,#A6192E,None,None,155,517,0,58,D,D,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,0,David Savard,72,239,311,239,311,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
2,15036327,8475233,David,Savard,12:28,13:11,00:43,1,3,MTL,8,Montréal Canadiens,2024020858,#A6192E,None,None,301,517,0,58,D,D,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,0,David Savard,43,748,791,748,791,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
3,15036762,8475233,David,Savard,15:11,16:30,01:19,1,4,MTL,8,Montréal Canadiens,2024020858,#A6192E,None,None,333,517,0,58,D,D,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,0,David Savard,79,911,990,911,990,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
4,15036763,8475233,David,Savard,18:18,19:03,00:45,1,5,MTL,8,Montréal Canadiens,2024020858,#A6192E,None,None,426,517,0,58,D,D,https://assets.nhle.com/mugs/nhl/20242025/MTL/...,0,David Savard,45,1098,1143,1098,1143,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,15038982,8484911,Collin,Graf,07:35,09:04,01:29,3,20,SJS,28,San Jose Sharks,2024020858,#006272,None,None,866,517,0,51,R,F,https://assets.nhle.com/mugs/nhl/20242025/SJS/...,1,Collin Graf,89,455,544,2855,2944,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
671,15039136,8484911,Collin,Graf,10:27,11:47,01:20,3,21,SJS,28,San Jose Sharks,2024020858,#006272,None,None,896,517,0,51,R,F,https://assets.nhle.com/mugs/nhl/20242025/SJS/...,1,Collin Graf,80,627,707,3027,3107,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
672,15039137,8484911,Collin,Graf,15:34,15:56,00:22,3,22,SJS,28,San Jose Sharks,2024020858,#006272,None,None,955,517,0,51,R,F,https://assets.nhle.com/mugs/nhl/20242025/SJS/...,1,Collin Graf,22,934,956,3334,3356,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
673,15039138,8484911,Collin,Graf,16:33,17:27,00:54,3,23,SJS,28,San Jose Sharks,2024020858,#006272,None,None,967,517,0,51,R,F,https://assets.nhle.com/mugs/nhl/20242025/SJS/...,1,Collin Graf,54,993,1047,3393,3447,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API
674,15039185,8484911,Collin,Graf,18:48,19:24,00:36,3,24,SJS,28,San Jose Sharks,2024020858,#006272,None,None,989,517,0,51,R,F,https://assets.nhle.com/mugs/nhl/20242025/SJS/...,1,Collin Graf,36,1128,1164,3528,3564,2025-02-04,2,20242025,2025-02-13 18:36:15.993953,NHL API